/**
 * Opt-in real, disposable LOCAL PostgreSQL: the closed-epoch repair through
 * the operator's shell against the production dialect, on 0x0e1ca0's real
 * chain history (testdata/closed-epoch-0e1ca0.json). Never reads DATABASE_URL.
 *
 * What only Postgres can show: a connection opened with
 * default_transaction_read_only that the server holds to; REPEATABLE READ
 * READ ONLY and SERIALIZABLE, each proved by current_setting; grant_json as
 * JSONB read as written (->>); the epoch bounds' millisecond-or-second
 * normalisation as integer division on BIGINT; pg_index read inside the
 * apply's transaction; INSERT … ON CONFLICT DO NOTHING RETURNING against the
 * partial flows_chain_identity; the receipts' partial unique index; the
 * agents row lock (a writer holding it makes the apply wait, then refuse,
 * writing nothing); and the revert's explicit-id re-insert into flows.id,
 * BIGINT GENERATED BY DEFAULT AS IDENTITY.
 *
 * Each run creates its own database and drops it. Run with
 * MERRYMEN_TEST_PG_URL=postgres://…@127.0.0.1:<port>/<db> and the `pg`
 * driver resolvable (NODE_PATH works: it is loaded with require here).
 */
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { createRequire } from "node:module";
import { existsSync, mkdtempSync, readFileSync, realpathSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { CASH, GRANT_PONS_CLASS } from "../../packages/core/src/index";
import { translateQuery, translateSchema, type Db } from "./db";
import { applyLedgerSchema } from "./store";
import { MIRROR_STATE_DDL } from "./ledger-mirror";
import { PAPER_CHECKPOINT_SCHEMA } from "./paper-checkpoint";
import { CHAIN_REFUSAL, knownChainFacts, planAttestedSeed } from "./ledger-resume";
import { ensureLedgerResumeSchema } from "./ledger-import";
import type { RpcCall } from "./chain-capital";
import { BookingRefused } from "./chain-gap-booking";
import type { PgClient } from "./chain-gap-booking-cli";
import { REPAIRS_TABLE } from "./closed-epoch-capital";
import { connectClosedEpoch, main } from "./closed-epoch-capital-cli";

const url = process.env.MERRYMEN_TEST_PG_URL ?? process.env.MERRYMEN_TEST_POSTGRES_URL;
const loadPg = async () => createRequire(import.meta.url)("pg") as unknown;

type FixtureLog = [string, string[], string, string];
const FX = JSON.parse(readFileSync(new URL("./testdata/closed-epoch-0e1ca0.json", import.meta.url), "utf8")) as {
  head: number; txs: Array<{ tx: string; block: string; blockHash: string; timestamp: number; from: string; to: string | null; status: string; logs: FixtureLog[] }>;
};
const TENANT = "0x0e1ca00202df6e686ac2317e10ed8ee8ae5e320d";
const ACCOUNT = "0x88e47214b5a0ca488cdabb4c9c28c3b71441ba78", SPELLED = "0x88e47214B5a0cA488cDABB4c9C28c3B71441BA78";
const CLASS_VAULT = "0xc730419217884328b7944b2504423e1a3a078c17";
const MU = "0xff080c8ce2e5feadaca0da81314ae59d232d4afd";
const DEPOSIT_TX = "0xc8ab6c45c87afb3d563b098bbee02d46bfb44f459976c7e142f9a32be8ade6c5";
const SWEEP_TX = "0xffd1143ee9ed3bce4cc9be603391433d28b5c15e5fa181305ab94f1f4369dfb1";
const DEPOSIT_AT = 1789515138, SWEEP_AT = 1789592963, EPOCH2_AT = 1789593711;
const USDG = String(CASH.USDG).toLowerCase();
const EP = "0x0000000071727de22e5e9d8baf0edac6f37da032";
const UOE = "0x49628fd1471006c1482da88028e9ce4dbb080b815c9b0344d39e5a8e6ec1419f";
const word = (n: bigint) => n.toString(16).padStart(64, "0");
const h32 = (s: string) => `0x${createHash("sha256").update(s).digest("hex")}`;
const topic = (a: string) => `0x${a.toLowerCase().replace(/^0x/, "").padStart(64, "0")}`;

const TXS = FX.txs.map((t) => ({ ...t, block: BigInt(t.block) }));
const POINTS = [...new Map(TXS.map((t) => [t.block, t.timestamp])).entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1));
const timeOf = (b: bigint): number => {
  const first = POINTS[0]!, last = POINTS[POINTS.length - 1]!;
  if (b <= first[0]) return first[1] - Math.ceil(Number(first[0] - b) / 9.936);
  if (b >= last[0]) return last[1] + Math.floor(Number(b - last[0]) / 9.936);
  for (let i = 1; i < POINTS.length; i++) {
    const [b1, t1] = POINTS[i]!, [b0, t0] = POINTS[i - 1]!;
    if (b <= b1) return t0 + Math.floor((t1 - t0) * Number(b - b0) / Number(b1 - b0));
  }
  return last[1];
};
const HEAD = BigInt(FX.head), NOW = timeOf(HEAD) + 600;
/** The public node, as the model: 10M-block spans at most, every receipt and block as read, every balance flat at the pinned block. */
const rpc: RpcCall = async (method, params) => {
  const blockOf = (b: bigint) => {
    const real = TXS.find((t) => t.block === b);
    return { number: `0x${b.toString(16)}`, hash: real?.blockHash ?? h32(`block ${b}`), timestamp: `0x${(real?.timestamp ?? timeOf(b)).toString(16)}` };
  };
  const logsOf = (t: (typeof TXS)[number]) => t.logs.map(([address, topics, data, logIndex]) => ({ address, topics, data, logIndex, blockNumber: `0x${t.block.toString(16)}`, transactionHash: t.tx }));
  if (method === "eth_chainId") return "0x1237";
  if (method === "eth_blockNumber") return `0x${HEAD.toString(16)}`;
  if (method === "eth_getBlockByNumber") return blockOf(BigInt(params[0] as string));
  if (method === "eth_getLogs") {
    const f = params[0] as { address: string; fromBlock: string; toBlock: string; topics: Array<string | null> };
    if (BigInt(f.toBlock) - BigInt(f.fromBlock) + 1n > 10_000_000n) throw new Error("query spans too many blocks; narrow the block range");
    return TXS.filter((t) => t.block >= BigInt(f.fromBlock) && t.block <= BigInt(f.toBlock)).flatMap(logsOf)
      .filter((l) => l.address.toLowerCase() === f.address.toLowerCase() && f.topics.every((x, i) => x === null || x.toLowerCase() === String(l.topics[i]).toLowerCase()));
  }
  if (method === "eth_getTransactionReceipt") {
    const t = TXS.find((x) => x.tx === params[0])!;
    return { status: t.status, blockNumber: `0x${t.block.toString(16)}`, blockHash: blockOf(t.block).hash, from: t.from, to: t.to, logs: logsOf(t) };
  }
  if (method === "eth_call") return `0x${word(0n)}`;
  throw new Error(method);
};

test("Postgres: preview read-only, apply once (SERIALIZABLE), revert exactly — 0x0e1ca0 through the operator's shell", { skip: !url, timeout: 120_000 }, async (t) => {
  const target = new URL(url!);
  assert.ok(["127.0.0.1", "localhost", "[::1]"].includes(target.hostname), "only a disposable LOCAL PostgreSQL is allowed");
  const pg = (await loadPg()) as { Client: new (c: { connectionString: string }) => PgClient & { connect(): Promise<void> } };
  const name = `mm_closed_epoch_${randomBytes(6).toString("hex")}`;
  const admin = new pg.Client({ connectionString: target.toString() }); await admin.connect();
  await admin.query(`CREATE DATABASE ${name}`);
  const scoped = new URL(target); scoped.pathname = `/${name}`;
  const clients: PgClient[] = [];
  const tmp = realpathSync(mkdtempSync(path.join(os.tmpdir(), "mm-closed-epoch-pg-")));
  t.after(async () => {
    await Promise.allSettled(clients.map((c) => c.end()));
    try { await admin.query(`DROP DATABASE ${name} WITH (FORCE)`); } finally { await admin.end(); rmSync(tmp, { recursive: true, force: true }); }
  });
  const setup = new pg.Client({ connectionString: scoped.toString() }); await setup.connect(); clients.push(setup);
  const db: Db = {
    prepare(sql) { return {
      async run(...a) { const r = await setup.query(translateQuery(sql), a); return { changes: r.rowCount ?? 0, lastInsertRowid: 0 }; },
      async get(...a) { return (await setup.query(translateQuery(sql), a)).rows[0]; },
      async all(...a) { return (await setup.query(translateQuery(sql), a)).rows; },
    }; },
    async exec(sql) { await setup.query(translateSchema(sql)); },
    async tx() { throw new Error("not here"); },
  };
  await applyLedgerSchema(db); await db.exec(MIRROR_STATE_DDL); await db.exec(PAPER_CHECKPOINT_SCHEMA);
  await setup.query(`CREATE TABLE grants (tenant TEXT PRIMARY KEY, chain_id INTEGER NOT NULL, grant_json JSONB NOT NULL, sealed_session_key TEXT, updated_at BIGINT NOT NULL)`);
  await setup.query("INSERT INTO grants VALUES ($1, 4663, $2, 'SEALED-NEVER-READ', 1)", [TENANT, JSON.stringify({ smartAccount: SPELLED, owner: TENANT, chainId: 4663,
    grantFeatures: ["tradeable-v2", GRANT_PONS_CLASS], ponsClassVaultAddress: CLASS_VAULT, serialized: "never-read" })]);
  await setup.query(`INSERT INTO agents (smart_account, owner_address, session_key_address, chain_id, caps, granted_at, expires_at, status, epoch, hwm_usdg, hwm_withdrawn_usdg, mode, beat_at)
    VALUES ($1, $2, $3, 4663, '{}', 1, 9999999999, 'armed', 2, 145.579752, 0, 'paper', 1789829679)`, [SPELLED, TENANT, `0x${"01".repeat(20)}`]);
  for (const tx of TXS) {
    for (const l of tx.logs.filter((x) => x[0] === EP && x[1][0] === UOE && x[1][2] === topic(ACCOUNT))) {
      const sweep = tx.tx === SWEEP_TX;
      await setup.query(`INSERT INTO trades (agent_id, kind, target, amount_usdg, user_op_hash, tx_hash, status, created_at, epoch) VALUES ($1, 'swap', $1, $2, $3, $4, 'landed', $5, 1)`,
        [SPELLED, sweep ? 144.81853 : 5, l[1][1], tx.tx, sweep ? SWEEP_AT + 630 : tx.timestamp]);
    }
  }
  for (const [at, epoch, mode, eth, cash] of [[DEPOSIT_AT + 62, 1, "live", "1000", 0.68], [1789593300, 1, "live", "1000", 0.68], [EPOCH2_AT, 2, "paper", "0", 1000]] as const) {
    await setup.query(`INSERT INTO equity (agent_id, eth_wei, cash_usdg, vault_usdg, positions_usdg, equity_usdg, epoch, mode, flows_held, cash_read_at, at) VALUES ($1, $2, $3, 0, 0, $3, $4, $5, 0, $6, $6)`,
      [SPELLED, eth, cash, epoch, mode, at]);
  }
  // A row carried in with a MILLISECOND stamp, filed in epoch 2 ten seconds before its paper opening: the bounds read it as seconds.
  await setup.query(`INSERT INTO fee_accruals (agent_id, profit_usdg, fee_usdg, hwm_before_usdg, hwm_after_usdg, epoch, at) VALUES ($1, 0, 0, 0, 0, 2, $2)`, [SPELLED, (EPOCH2_AT - 10) * 1000]);
  await setup.query(`INSERT INTO positions (agent_id, symbol, token, raw_balance, ui_multiplier, price_usd, price_stale, value_usdg, updated_at) VALUES ($1, 'MU', $2, '5365685809818', '1', 1, 0, 1, 1789592749)`,
    [SPELLED, MU]);
  await setup.query("INSERT INTO cost_basis (agent_id, mode, symbol, qty_raw, cost_usdg, updated_at) VALUES ($1, 'live', 'MU', '5365685809818', '5026', 1789590627)", [SPELLED]);
  await setup.query("INSERT INTO position_floors (agent_id, mode, symbol, stop_bps, rung, why, at) VALUES ($1, 'live', 'MU', 1500, 'standard', 'graded at entry', 1789556100)", [SPELLED]);
  // An inferred stand-in in epoch 1, for the quarantine and the revert's explicit-id re-insert.
  const inferredId = Number((await setup.query(`INSERT INTO flows (agent_id, direction, amount_usdg, source, epoch, chain_id, at) VALUES ($1, 'in', 145.499004, 'inferred', 1, 4663, $2) RETURNING id`,
    [SPELLED, DEPOSIT_AT + 200])).rows[0]!.id);
  for (const table of ["trades", "flows", "equity", "events"]) {
    await setup.query("INSERT INTO mirror_state (tenant, table_name, last_id, last_stamp, updated_at) VALUES ($1, $2, 9, $3, 1789829702)", [TENANT, table, EPOCH2_AT]);
  }
  await ensureLedgerResumeSchema(db);
  await setup.query(`INSERT INTO ledger_resume_approvals (approval_id, tenant, smart_account, chain_id, owner, evidence_digest, evidence_json, preview_run, state, reason,
      created_at_ms, updated_at_ms, chain_read_from_sec) VALUES ('8d1c4c6b', $1, $2, 4663, $1, $3, '{}', 'r', 'refused', $4, 1791248849249, 1791250434038, 1789238789)`,
  [TENANT, ACCOUNT, "e".repeat(64), `${CHAIN_REFUSAL}: USDG in 145.499004 in tx ${DEPOSIT_TX} log 0 at block 64045884`]);

  // THE SERVER HOLDS THE READ-ONLY CONNECTION TO IT, whatever the shell lets through.
  const ro = await connectClosedEpoch(scoped.toString(), true, loadPg); clients.push(ro);
  await assert.rejects(ro.query("INSERT INTO events (agent_id, message) VALUES ('x', 'y')"), /read-only transaction/);
  // Read after the shell's connection set the driver's BIGINT parser (process-wide), so both sides read numbers alike.
  const flowsBefore = (await setup.query("SELECT * FROM flows ORDER BY id")).rows;

  const printed: string[] = [];
  const deps = { connect: (u: string, r: boolean) => connectClosedEpoch(u, r, loadPg), rpc, nowMs: () => NOW * 1000, out: (l: string) => printed.push(l), source: { test: "pg" },
    sleep: async () => {} };
  const env = { DATABASE_URL: scoped.toString() };
  const previewFile = path.join(tmp, "preview.json");
  assert.equal(await main(["--tenant", TENANT, "--epoch", "1", "--output", previewFile], env, deps), 0, printed.join("\n"));
  const plan = JSON.parse(readFileSync(previewFile, "utf8")) as { verdict: string; previewDigest: string; boundary: { upperSec: number; witness: { kind: string } };
    proposals: { inserts: Array<{ key: string }>; quarantines: Array<{ id: number }>; clears: Array<{ kind: string }> } };
  assert.equal(plan.verdict, "ready");
  assert.deepEqual(plan.proposals.inserts.map((i) => i.key), [`log:${DEPOSIT_TX}#0`, `log:${SWEEP_TX}#7`]);
  assert.deepEqual(plan.proposals.quarantines.map((q) => q.id), [inferredId]);
  assert.deepEqual(plan.proposals.clears.map((c) => c.kind), ["clear-live-basis", "clear-live-floor"]);
  assert.deepEqual([plan.boundary.upperSec, plan.boundary.witness.kind], [EPOCH2_AT - 10, "W1"], "the millisecond stamp, read as seconds, closes epoch 1 ten seconds earlier");
  assert.equal(Number((await setup.query("SELECT COUNT(*) AS n FROM flows")).rows[0]!.n), 1, "the preview wrote nothing");

  // THE AGENT ROW LOCK: a writer holding it makes the apply wait (lock_timeout 5s), then refuse, writing nothing and leaving no report.
  const holder = new pg.Client({ connectionString: scoped.toString() }); await holder.connect(); clients.push(holder);
  await holder.query("BEGIN");
  await holder.query("SELECT epoch FROM agents WHERE smart_account = $1 FOR UPDATE", [SPELLED]);
  const blocked = path.join(tmp, "blocked.json");
  await assert.rejects(main(["--tenant", TENANT, "--epoch", "1", "--apply", "--confirm", plan.previewDigest, "--backup-ref", "pg-local-drill", "--output", blocked], env, deps),
    (e: unknown) => (e as { code?: unknown }).code === "55P03");
  await holder.query("ROLLBACK");
  assert.equal(existsSync(blocked), false);
  assert.equal(Number((await setup.query("SELECT COUNT(*) AS n FROM flows")).rows[0]!.n), 1);

  const applied = path.join(tmp, "apply.json");
  assert.equal(await main(["--tenant", TENANT, "--epoch", "1", "--apply", "--confirm", plan.previewDigest, "--backup-ref", "pg-local-drill", "--output", applied], env, deps), 0, printed.join("\n"));
  const report = JSON.parse(readFileSync(applied, "utf8")) as { repairId: string; actions: Array<{ action: string; evidenceKey: string }> };
  const flows = (await setup.query("SELECT direction, amount_usdg, tx_hash, block_number, log_index, source, epoch, chain_id, at FROM flows ORDER BY id")).rows;
  assert.deepEqual(flows.map((f) => [f.direction, Number(f.amount_usdg), f.tx_hash, Number(f.block_number), Number(f.log_index), f.source, Number(f.epoch), Number(f.chain_id), Number(f.at)]), [
    ["in", 145.499004, DEPOSIT_TX, 64045884, 0, "chain-log", 1, 4663, DEPOSIT_AT], ["out", 144.81853, SWEEP_TX, 64819173, 7, "chain-log", 1, 4663, SWEEP_AT]]);
  assert.deepEqual((await setup.query("SELECT original_id, run_id, source FROM flows_quarantine")).rows.map((r) => [Number(r.original_id), r.run_id, r.source]),
    [[inferredId, report.repairId, "inferred"]]);
  assert.equal(Number((await setup.query("SELECT COUNT(*) AS n FROM cost_basis")).rows[0]!.n), 0);
  assert.deepEqual(await planAttestedSeed(db, SPELLED), { basis: [], floors: [] });
  const k = await knownChainFacts(db, ACCOUNT);
  assert.ok(k.flows.has(`${DEPOSIT_TX}:0`) && k.flows.has(`${SWEEP_TX}:7`), "what admission's chain check reads now answers the deposit");
  // THE RECEIPTS' KEY: a second applied receipt of the same evidence, in any epoch, is refused by the server.
  await assert.rejects(setup.query(`INSERT INTO ${REPAIRS_TABLE} (repair_id, tenant, account, epoch, chain_id, action, evidence_key, table_name, row_key, row_json, row_digest,
    preview_digest, backup_ref, admission_json, fingerprints_json, state, applied_at_ms) VALUES ('other', $1, $2, 2, 4663, 'insert-flow', $3, 'flows', '{}', '{}', 'd', 'p', 'b', '{}', '{}', 'applied', 1)`,
  [TENANT, ACCOUNT, `log:${DEPOSIT_TX}#0`]), /duplicate key/);
  // THE FLOWS IDENTITY: the same log again, under ON CONFLICT DO NOTHING RETURNING, returns no id.
  const again = await setup.query(`INSERT INTO flows (agent_id, direction, amount_usdg, tx_hash, block_number, log_index, source, epoch, chain_id, at)
    VALUES ($1, 'in', 145.499004, $2, 64045884, 0, 'chain-log', 2, 4663, 1) ON CONFLICT DO NOTHING RETURNING id`, [SPELLED, DEPOSIT_TX]);
  assert.equal(again.rows.length, 0);
  // Applied once: a second apply finds nothing to do.
  await assert.rejects(main(["--tenant", TENANT, "--epoch", "1", "--apply", "--confirm", plan.previewDigest, "--backup-ref", "pg-local-drill", "--output", path.join(tmp, "twice.json")], env, deps),
    (e: unknown) => e instanceof BookingRefused && e.code === "nothing-to-do");

  // REVERT FROM THE RECEIPTS ALONE: the stand-in back under its original id (an explicit id into the identity column), the basis back, the quarantine row kept.
  assert.equal(await main(["--revert-repair", report.repairId, "--output", path.join(tmp, "revert.json")], env, deps), 0, printed.join("\n"));
  assert.deepEqual((await setup.query("SELECT * FROM flows ORDER BY id")).rows, flowsBefore);
  assert.equal(Number((await setup.query("SELECT COUNT(*) AS n FROM flows_quarantine")).rows[0]!.n), 1);
  assert.deepEqual((await setup.query("SELECT qty_raw, cost_usdg, updated_at FROM cost_basis")).rows.map((r) => [r.qty_raw, r.cost_usdg, Number(r.updated_at)]), [["5365685809818", "5026", 1789590627]]);
  assert.deepEqual((await setup.query(`SELECT DISTINCT state FROM ${REPAIRS_TABLE}`)).rows, [{ state: "reverted" }]);
  // The identity column still hands out fresh ids after the explicit one.
  const fresh = Number((await setup.query(`INSERT INTO flows (agent_id, direction, amount_usdg, source, epoch, at) VALUES ($1, 'in', 1, 'inferred', 2, 1) RETURNING id`, [SPELLED])).rows[0]!.id);
  assert.ok(fresh > inferredId);
  assert.ok(printed.every((l) => !l.includes(scoped.toString())), "the URL is never printed");
});
