package dev.merrymen.app.net

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import okhttp3.FormBody
import okhttp3.MediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody
import okhttp3.Response
import java.io.IOException
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine

/**
 * EVERY ENDPOINT THE PRODUCT HAS, IN ONE PLACE.
 *
 * Hand-rolled over OkHttp rather than generated by Retrofit, for one reason
 * that matters here: the origin is a RUNTIME value. A tenant can point this app
 * at the hosted service, a staging deploy or a laptop, and Retrofit fixes its
 * base URL when the instance is built. Rebuilding the whole stack on every
 * origin change is a bigger moving part than composing a URL.
 *
 * WHAT A FAILURE IS. `ApiResult` distinguishes three things the UI must never
 * collapse: a value, a refusal the server explained (with its status, so 401
 * "sign in" and 503 "we could not read" stay apart), and a transport failure
 * that is ours. The screens render all three differently, because "you hold
 * nothing", "you are not signed in" and "we could not check" have three
 * different remedies and only one of them is about the reader.
 */
sealed interface ApiResult<out T> {
  data class Ok<T>(val value: T) : ApiResult<T>
  /** The server answered, and said no. `status` is load-bearing. */
  data class Refused(val status: Int, val message: String) : ApiResult<Nothing>
  /** We never got an answer. Not the same as being told no. */
  data class Unreachable(val cause: String) : ApiResult<Nothing>
}

inline fun <T, R> ApiResult<T>.map(f: (T) -> R): ApiResult<R> = when (this) {
  is ApiResult.Ok -> ApiResult.Ok(f(value))
  is ApiResult.Refused -> this
  is ApiResult.Unreachable -> this
}

fun <T> ApiResult<T>.valueOrNull(): T? = (this as? ApiResult.Ok)?.value

class MerrymenApi(private val http: OkHttpClient, private val session: Session) {

  val json = Json {
    ignoreUnknownKeys = true
    explicitNulls = false
    isLenient = true
    coerceInputValues = false
  }

  private val jsonType: MediaType = MediaType.get("application/json; charset=utf-8")

  // ── plumbing ──────────────────────────────────────────────────────────────

  private suspend fun url(path: String): String = session.originNow() + path

  private suspend fun call(req: Request): ApiResult<String> = suspendCoroutine { cont ->
    http.newCall(req).enqueue(object : okhttp3.Callback {
      override fun onFailure(call: okhttp3.Call, e: IOException) {
        cont.resume(ApiResult.Unreachable(e.message ?: e.javaClass.simpleName))
      }

      override fun onResponse(call: okhttp3.Call, response: Response) {
        response.use { r ->
          val body = try {
            r.body()?.string().orEmpty()
          } catch (e: IOException) {
            cont.resume(ApiResult.Unreachable(e.message ?: "read failed"))
            return
          }
          if (r.isSuccessful) {
            cont.resume(ApiResult.Ok(body))
          } else {
            // The API answers with several error shapes, and two routes answer
            // in PLAIN TEXT (the middleware's host and cross-site refusals).
            // Try JSON, fall back to the raw body, never invent a sentence.
            val msg = runCatching { json.decodeFromString<ApiError>(body) }
              .getOrNull()?.let { it.error ?: it.detail }
              ?: body.ifBlank { "HTTP ${r.code()}" }
            cont.resume(ApiResult.Refused(r.code(), msg))
          }
        }
      }
    })
    cont.context // keep the continuation referenced for clarity
  }

  private suspend inline fun <reified T> getJson(path: String): ApiResult<T> =
    call(Request.Builder().url(url(path)).get().build()).map { json.decodeFromString<T>(it) }

  private suspend inline fun <reified T> sendJson(
    path: String,
    method: String,
    bodyJson: String?,
  ): ApiResult<T> {
    val body: RequestBody = RequestBody.create(jsonType, bodyJson ?: "{}")
    val req = Request.Builder().url(url(path)).method(method, body).build()
    return call(req).map { json.decodeFromString<T>(it) }
  }

  // ── the doorknob ──────────────────────────────────────────────────────────

  /**
   * POST /api/gate — FORM DATA, not JSON, and it answers 303.
   *
   * The whole deployment sits behind this while it is in beta: every /api/*
   * path except this one returns 401 {"error":"gated"} without the cookie. The
   * password is checked with a constant-time compare and the cookie value IS
   * the password, so it is stored the way a password is.
   */
  suspend fun gate(password: String): ApiResult<Unit> {
    val form = FormBody.Builder().add("password", password).build()
    val req = Request.Builder().url(url("/api/gate")).post(form).build()
    // A 303 is the SUCCESS shape here, and OkHttp follows redirects by default,
    // so the cookie is captured by the jar on the way through.
    return call(req).map { }
  }

  // ── sign-in ───────────────────────────────────────────────────────────────

  suspend fun challenge(): ApiResult<Challenge> = getJson("/api/auth/challenge")

  suspend fun verify(address: String, signature: String, nonce: String): ApiResult<VerifyResult> =
    sendJson("/api/auth/verify", "POST", json.encodeToString(VerifyBody.serializer(), VerifyBody(address, signature, nonce)))

  // ── read: who am I, what do I hold ───────────────────────────────────────

  suspend fun version(): ApiResult<Version> = getJson("/api/version")
  suspend fun feed(): ApiResult<Feed> = getJson("/api/feed")
  suspend fun scoreboard(): ApiResult<JsonElement> = getJson("/api/scoreboard")
  suspend fun grants(): ApiResult<GrantView> = getJson("/api/grants")
  suspend fun proposals(): ApiResult<ProposalsView> = getJson("/api/proposals")

  // ── read: the world ───────────────────────────────────────────────────────

  suspend fun theses(): ApiResult<ThesesPage> = getJson("/api/theses")
  suspend fun tokens(): ApiResult<TokensPage> = getJson("/api/tokens")
  suspend fun market(): ApiResult<JsonElement> = getJson("/api/market")
  suspend fun leaderboard(): ApiResult<Leaderboard> = getJson("/api/leaderboard")
  suspend fun agents(): ApiResult<JsonElement> = getJson("/api/agents")
  suspend fun discoveries(): ApiResult<JsonElement> = getJson("/api/discoveries")
  suspend fun venue(): ApiResult<JsonElement> = getJson("/api/venue")
  suspend fun wall(): ApiResult<JsonElement> = getJson("/api/wall")
  suspend fun wallTape(): ApiResult<JsonElement> = getJson("/api/wall-tape")
  suspend fun likeCounts(): ApiResult<JsonElement> = getJson("/api/like-counts")

  suspend fun search(q: String): ApiResult<SearchResults> =
    getJson("/api/search?q=" + java.net.URLEncoder.encode(q, "UTF-8"))

  // ── the Circle ────────────────────────────────────────────────────────────

  suspend fun tier(): ApiResult<TierView> = getJson("/api/tier")
  suspend fun circle(): ApiResult<CircleView> = getJson("/api/circle")
  suspend fun alpha(): ApiResult<AlphaView> = getJson("/api/alpha")

  /** GET returns a challenge to sign; PATCH reads back what is linked. */
  suspend fun holderChallenge(holder: String): ApiResult<HolderChallenge> =
    getJson("/api/holder?holder=" + java.net.URLEncoder.encode(holder, "UTF-8"))

  suspend fun holderLinked(): ApiResult<HolderLinked> = sendJson("/api/holder", "PATCH", "{}")

  suspend fun holderUnlink(): ApiResult<JsonElement> = sendJson("/api/holder", "DELETE", null)

  // ── settings ──────────────────────────────────────────────────────────────

  suspend fun settings(): ApiResult<SettingsEnvelope> = getJson("/api/settings")

  /**
   * The WHOLE object goes back, not a patch.
   *
   * `values` is what the server handed us with the edits applied on top. Sending
   * a subset is how a client silently unsets every field it does not know about
   * — see the note on SettingsEnvelope.
   */
  suspend fun saveSettings(whole: JsonElement): ApiResult<SettingsEnvelope> =
    sendJson("/api/settings", "PUT", json.encodeToString(JsonElement.serializer(), whole))

  // ── telegram ──────────────────────────────────────────────────────────────

  suspend fun telegram(): ApiResult<TelegramStatus> = getJson("/api/telegram")

  suspend fun telegramTest(token: String?): ApiResult<TelegramTest> =
    sendJson(
      "/api/telegram",
      "POST",
      json.encodeToString(TelegramTestBody.serializer(), TelegramTestBody(token = token)),
    )

  // ── acting ────────────────────────────────────────────────────────────────

  suspend fun chat(body: ChatBody): ApiResult<ChatReply> =
    sendJson("/api/chat", "POST", json.encodeToString(ChatBody.serializer(), body))

  suspend fun order(side: String, symbol: String, usdg: Double): ApiResult<OrderResult> =
    sendJson("/api/orders", "POST", json.encodeToString(OrderBody.serializer(), OrderBody(side, symbol, usdg)))

  suspend fun orderStatus(): ApiResult<OrderResult> = getJson("/api/orders")

  suspend fun snipe(query: String, usdg: Double): ApiResult<JsonElement> =
    sendJson("/api/snipe", "POST", json.encodeToString(SnipeBody.serializer(), SnipeBody(query, usdg)))

  suspend fun selftest(): ApiResult<OrderResult> = sendJson("/api/selftest", "POST", null)
  suspend fun selftestStatus(): ApiResult<JsonElement> = getJson("/api/selftest")

  /** Practice book only. The worker refuses this outright on the live rail. */
  suspend fun paperReset(): ApiResult<OrderResult> = sendJson("/api/paper-reset", "POST", null)

  suspend fun models(): ApiResult<JsonElement> = sendJson("/api/models", "POST", "{}")

  suspend fun follow(slug: String, on: Boolean): ApiResult<JsonElement> =
    sendJson("/api/follow", "POST", """{"slug":"$slug","follow":$on}""")

  suspend fun like(postId: String, on: Boolean): ApiResult<JsonElement> =
    sendJson("/api/likes", "POST", """{"postId":"$postId","like":$on}""")

  /**
   * THE KILL SWITCH. Removes the grant, which stands the worker down.
   *
   * Kept beside the reads rather than hidden, because a stop control that is
   * hard to find is not a stop control.
   */
  suspend fun revokeGrant(): ApiResult<JsonElement> = sendJson("/api/grants", "DELETE", null)
}
