package dev.merrymen.app.net

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import okhttp3.MediaType
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody
import okhttp3.Response
import java.io.IOException
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine

/**
 * EVERY ENDPOINT THE PRODUCT HAS, IN ONE PLACE.
 *
 * Hand-rolled over OkHttp rather than generated by Retrofit, for one reason
 * that matters here: the origin is a RUNTIME value. A tenant can point this app
 * at the hosted service, a staging deploy or a laptop, and Retrofit fixes its
 * base URL when the instance is built. Rebuilding the whole stack on every
 * origin change is a bigger moving part than composing a URL.
 *
 * WHAT A FAILURE IS. `ApiResult` distinguishes three things the UI must never
 * collapse: a value, a refusal the server explained (with its status, so 401
 * "sign in" and 503 "we could not read" stay apart), and a transport failure
 * that is ours. The screens render all three differently, because "you hold
 * nothing", "you are not signed in" and "we could not check" have three
 * different remedies and only one of them is about the reader.
 */
sealed interface ApiResult<out T> {
  data class Ok<T>(val value: T) : ApiResult<T>
  /**
   * The server answered, and said no. `status` is load-bearing. `message` is a
   * sentence the server wrote for a person, or "HTTP <code>" / the generic 5xx
   * line when it wrote none — never a raw body.
   *
   * [retryAfterSec] is the Retry-After header in seconds, when a rate limit
   * sent one (group chat's 429 does), so "slow down, try again in 7s" can say
   * the real number instead of a guess. Null when absent or not in seconds.
   */
  data class Refused(val status: Int, val message: String, val retryAfterSec: Long? = null) : ApiResult<Nothing>
  /**
   * We never got an answer we could read. Not the same as being told no.
   *
   * That includes a 2xx whose body would not decode: the server may well have
   * done the thing, we just cannot say what it said. So for a WRITE this is an
   * UNKNOWN outcome, never a failure — an order whose answer was lost may
   * exist, and the caller must look it up rather than tell the owner it failed.
   */
  data class Unreachable(val cause: String) : ApiResult<Nothing>
}

inline fun <T, R> ApiResult<T>.map(f: (T) -> R): ApiResult<R> = when (this) {
  is ApiResult.Ok -> ApiResult.Ok(f(value))
  is ApiResult.Refused -> this
  is ApiResult.Unreachable -> this
}

fun <T> ApiResult<T>.valueOrNull(): T? = (this as? ApiResult.Ok)?.value

/**
 * WHERE THE SERVER IS, asked at the moment of each call.
 *
 * An interface rather than [Session] itself so the whole client runs on the
 * JVM: Session needs an Android Context for its DataStore, and a unit test
 * wants to point the real [MerrymenApi] — its decoding, its refusal wording —
 * at a MockWebServer without an emulator. Session implements it for the app.
 */
fun interface OriginSource {
  /** The origin with no trailing slash, so a path can be appended as-is. */
  suspend fun originNow(): String
}

/**
 * ADDING AN ENDPOINT. New routes do not go in this file. Write them as
 * extension functions in your own net/<Area>Wire.kt (OrdersWire.kt,
 * MarketWire.kt, …), over the plumbing below:
 *
 *   suspend fun MerrymenApi.ceiling(): ApiResult<Ceiling> = getJson("/api/orders/ceiling")
 *
 * getJson, sendJson, call, url and json are `@PublishedApi internal` for exactly
 * that, so a new route gets the same three-state result, the same refusal
 * wording and the same decode-failure handling as every route here, without
 * this file becoming everybody's merge conflict.
 */
class MerrymenApi(
  /** The shared client: one cookie jar, one connection pool, the app's headers. */
  val http: OkHttpClient,
  private val origins: OriginSource,
) {

  @PublishedApi internal val json = Json {
    ignoreUnknownKeys = true
    explicitNulls = false
    isLenient = true
    coerceInputValues = false
  }

  @PublishedApi internal val jsonType: MediaType = "application/json; charset=utf-8".toMediaType()

  /** The origin every call is made against right now — for building a web URL beside an API one. */
  suspend fun originNow(): String = origins.originNow()

  // ── plumbing ──────────────────────────────────────────────────────────────

  @PublishedApi internal suspend fun url(path: String): String = origins.originNow() + path

  /** One request, as the three-state result. [client] is [http] unless a route needs its own timeouts. */
  @PublishedApi internal suspend fun call(req: Request, client: OkHttpClient = http): ApiResult<String> =
    suspendCancellableCoroutine { cont ->
      // CANCELLABLE, so a screen that goes away takes its request with it.
      // suspendCoroutine leaked one in-flight call per abandoned LaunchedEffect.
      val theCall = client.newCall(req)
      cont.invokeOnCancellation { theCall.cancel() }
      theCall.enqueue(object : okhttp3.Callback {
        override fun onFailure(call: okhttp3.Call, e: IOException) {
          cont.resume(ApiResult.Unreachable(e.message ?: e.javaClass.simpleName))
        }

        override fun onResponse(call: okhttp3.Call, response: Response) {
          response.use { r ->
            val body = try {
              r.body?.string().orEmpty()
            } catch (e: IOException) {
              cont.resume(ApiResult.Unreachable(e.message ?: "read failed"))
              return
            }
            if (r.isSuccessful) {
              cont.resume(ApiResult.Ok(body))
            } else {
              val retryAfter = r.header("retry-after")?.trim()?.toLongOrNull()?.takeIf { it >= 0 }
              cont.resume(ApiResult.Refused(r.code, refusalMessage(r.code, body), retryAfter))
            }
          }
        }
      })
    }

  /**
   * WHAT A REFUSAL SAYS, in words a person was meant to read — or its status.
   *
   * A 4xx: the JSON's validation list (one line each, which is how /api/settings
   * and its read-modify-write callers refuse), else its error, detail or why. A
   * body with none of those — plain text from the middleware, a Next 404 page,
   * JSON that says nothing — gives "HTTP <code>" and is NEVER pasted in: a page
   * of markup in an amber notice is not a sentence, and it is somebody else's
   * words in ours.
   *
   * A 5xx is the server failing, and its body is usually a stack's words, so
   * it reads as one generic line — unless the route marked it `ownerFacing`,
   * which is how a 5xx written for the owner ("couldn't check this account's
   * ownership") says so. That is the web's rule too.
   */
  private fun refusalMessage(code: Int, body: String): String {
    val err = try {
      json.decodeFromString<ApiError>(body)
    } catch (e: IllegalArgumentException) {
      null
    }
    val said = err?.let {
      it.errors?.filter { e -> e.isNotBlank() }?.takeIf { e -> e.isNotEmpty() }?.joinToString("\n")
        ?: it.error?.takeIf { e -> e.isNotBlank() }
        ?: it.detail?.takeIf { e -> e.isNotBlank() }
        ?: it.why?.takeIf { e -> e.isNotBlank() }
    }
    return if (code >= 500) {
      if (err?.ownerFacing == true && said != null) said else "the server had a problem (HTTP $code)"
    } else {
      said ?: "HTTP $code"
    }
  }

  /**
   * A 2xx BODY THAT WILL NOT DECODE IS AN ANSWER WE COULD NOT READ — never a crash.
   *
   * It used to decode inside ApiResult.map with nothing catching, so an HTML
   * 200, a null where a model has a default, a missing required field or a
   * number past Int threw out of whichever LaunchedEffect asked, and the
   * process died on whatever screen was open. `IllegalArgumentException` is
   * what kotlinx.serialization throws for all of those (SerializationException
   * extends it).
   *
   * UNREACHABLE, NOT REFUSED, because nobody refused anything: see
   * [ApiResult.Unreachable] for what that means to a write. And coercion stays
   * off in [json]: coercing would read an unread null as the default, and for
   * a figure the default is a confident 0.
   */
  @PublishedApi internal inline fun <reified T> decoded(r: ApiResult<String>): ApiResult<T> = when (r) {
    is ApiResult.Ok -> try {
      ApiResult.Ok(json.decodeFromString<T>(r.value))
    } catch (e: IllegalArgumentException) {
      ApiResult.Unreachable("the server's answer could not be read (" + (T::class.simpleName ?: "?") + ")")
    }
    is ApiResult.Refused -> r
    is ApiResult.Unreachable -> r
  }

  @PublishedApi internal suspend inline fun <reified T> getJson(path: String): ApiResult<T> =
    decoded(call(Request.Builder().url(url(path)).get().build()))

  /** A JSON body (`{}` when null) with any method. [client] as on [call]. */
  @PublishedApi internal suspend inline fun <reified T> sendJson(
    path: String,
    method: String,
    bodyJson: String?,
    client: OkHttpClient = http,
  ): ApiResult<T> {
    val body: RequestBody = (bodyJson ?: "{}").toRequestBody(jsonType)
    val req = Request.Builder().url(url(path)).method(method, body).build()
    return decoded(call(req, client))
  }

  // ── sign-in ───────────────────────────────────────────────────────────────

  /** Who am I? The purpose-built read — "read-only, safe to poll". */
  suspend fun session(): ApiResult<SessionView> = getJson("/api/auth/session")

  /** Sign-out must invalidate the SERVER session, not just the local jar. */
  suspend fun logout(): ApiResult<JsonElement> = sendJson("/api/auth/logout", "POST", null)

  suspend fun challenge(): ApiResult<Challenge> = getJson("/api/auth/challenge")

  suspend fun verify(address: String, signature: String, nonce: String): ApiResult<VerifyResult> =
    sendJson("/api/auth/verify", "POST", json.encodeToString(VerifyBody.serializer(), VerifyBody(address, signature, nonce)))

  // ── read: who am I, what do I hold ───────────────────────────────────────

  suspend fun version(): ApiResult<Version> = getJson("/api/version")
  suspend fun feed(): ApiResult<Feed> = getJson("/api/feed")
  suspend fun scoreboard(): ApiResult<JsonElement> = getJson("/api/scoreboard")
  suspend fun grants(): ApiResult<GrantView> = getJson("/api/grants")
  suspend fun proposals(): ApiResult<ProposalsView> = getJson("/api/proposals")

  // ── read: the world ───────────────────────────────────────────────────────

  suspend fun theses(): ApiResult<ThesesPage> = getJson("/api/theses")
  // MARKETS IS /api/market. There is no /api/tokens list route — only
  // /api/tokens/{address} — so the old call was a 404 behind three screens.
  suspend fun market(): ApiResult<TokensPage> = getJson("/api/market")
  /**
   * ONE TOKEN, IN FULL: who holds it, what the index says, and its bars.
   *
   * The `window` the ROUTE takes is not the window the reader picked. It
   * accepts four bar sizes (15m, 1h, 4h, 1d) and anything else silently
   * becomes 1h; the six buttons are spans of history, which is a different
   * question. `barSize` below maps one to the other, and the span is applied
   * by trimming — never by padding.
   *
   * [activity] adds `&activity=1`, which makes the route attach pool evidence
   * (recent pool trades, the tape) to a COIN's answer as [TokenDetail.evidence].
   * Off by default: it is a second upstream read, and only the token page's
   * market-activity panel needs it.
   */
  suspend fun token(address: String, window: String = "1h", activity: Boolean = false): ApiResult<TokenDetail> =
    getJson("/api/tokens/" + address + "?window=" + window + (if (activity) "&activity=1" else ""))

  /**
   * A STOCK'S BARS, through our own proxy.
   *
   * Never Yahoo directly: the allow-list of symbols lives on the server and is
   * derived from the chain's own registry, so a chart we draw is always of an
   * instrument this chain actually lists. A client that composed the upstream
   * URL itself would be a free market-data relay wearing our domain.
   */
  suspend fun venueChart(symbol: String, window: String): ApiResult<VenueChart> =
    getJson(
      "/api/venue?desk=chart&symbol=" + java.net.URLEncoder.encode(symbol, "UTF-8") +
        "&window=" + java.net.URLEncoder.encode(window, "UTF-8"),
    )
  suspend fun leaderboard(): ApiResult<Leaderboard> = getJson("/api/leaderboard")
  suspend fun agent(slug: String): ApiResult<JsonElement> = getJson("/api/agents/" + slug)
  suspend fun discoveries(): ApiResult<Discoveries> = getJson("/api/discoveries")
  suspend fun venue(): ApiResult<JsonElement> = getJson("/api/venue")
  suspend fun wall(): ApiResult<JsonElement> = getJson("/api/wall")
  suspend fun wallTape(): ApiResult<JsonElement> = getJson("/api/wall-tape")
  /** Session-free by design, so it is cacheable and carries nobody's identity. */
  suspend fun likeCounts(): ApiResult<LikeCounts> = getJson("/api/like-counts")

  suspend fun search(q: String): ApiResult<SearchResults> =
    getJson("/api/search?q=" + java.net.URLEncoder.encode(q, "UTF-8"))

  // ── the Circle ────────────────────────────────────────────────────────────

  suspend fun tier(): ApiResult<TierView> = getJson("/api/tier")
  suspend fun circle(): ApiResult<CircleView> = getJson("/api/circle")
  suspend fun alpha(): ApiResult<AlphaView> = getJson("/api/alpha")

  /** GET returns a challenge to sign; PATCH reads back what is linked. */
  suspend fun holderChallenge(holder: String): ApiResult<HolderChallenge> =
    getJson("/api/holder?holder=" + java.net.URLEncoder.encode(holder, "UTF-8"))

  suspend fun holderLinked(): ApiResult<HolderLinked> = sendJson("/api/holder", "PATCH", "{}")

  suspend fun holderUnlink(): ApiResult<JsonElement> = sendJson("/api/holder", "DELETE", null)

  // ── settings ──────────────────────────────────────────────────────────────

  suspend fun settings(): ApiResult<SettingsEnvelope> = getJson("/api/settings")

  /**
   * A PATCH of only what the owner edited.
   *
   * The handler reads each field with `if ("name" in body)`, so omitted fields
   * are left alone. Sending the whole object back would echo masked secrets
   * (GET returns `set`/`hint`, never the value) and overwrite real keys with
   * asterisks.
   *
   * [owner] is the wallet the values being saved were READ for — the
   * [SettingsEnvelope.owner] of the GET behind this write, "" included when that
   * read was signed out. It is merged into the body; hosted, the server refuses
   * a mismatch with its session (409 OWNER_CHANGED_SETTING) and writes nothing,
   * so a form loaded for one wallet cannot save onto another. Null sends no
   * owner and the save is judged by session alone.
   */
  suspend fun patchSettings(patch: JsonElement, owner: String? = null): ApiResult<SettingsSaved> {
    val body = if (owner != null && patch is kotlinx.serialization.json.JsonObject) {
      kotlinx.serialization.json.JsonObject(patch + ("owner" to kotlinx.serialization.json.JsonPrimitive(owner)))
    } else {
      patch
    }
    return sendJson("/api/settings", "PUT", json.encodeToString(JsonElement.serializer(), body))
  }

  // ── telegram ──────────────────────────────────────────────────────────────

  suspend fun telegram(): ApiResult<TelegramStatus> = getJson("/api/telegram")

  suspend fun telegramTest(token: String?): ApiResult<TelegramTest> =
    sendJson(
      "/api/telegram",
      "POST",
      json.encodeToString(TelegramTestBody.serializer(), TelegramTestBody(token = token)),
    )

  // ── acting ────────────────────────────────────────────────────────────────

  /**
   * THE CHAT'S OWN CLIENT: the shared one, with the patience a model needs.
   *
   * A non-streamed /api/chat sends nothing until the whole completion is done,
   * and the web waits 60s for it. The shared client's 30s read timeout cut a
   * slow model off halfway and reported it as "Couldn't reach merrymen" — our
   * failure, invented out of the model thinking. 90s to read, 120s for the
   * whole call, so a reply the web would have waited for arrives here too and
   * a dead connection still ends.
   *
   * Derived with newBuilder, so it shares the cookie jar, the headers and the
   * connection pool. A streamed reader (SSE) should use this client as well.
   */
  val chatHttp: OkHttpClient by lazy {
    http.newBuilder()
      .readTimeout(90, java.util.concurrent.TimeUnit.SECONDS)
      .callTimeout(120, java.util.concurrent.TimeUnit.SECONDS)
      .build()
  }

  suspend fun chat(body: ChatBody): ApiResult<ChatReply> =
    sendJson("/api/chat", "POST", json.encodeToString(ChatBody.serializer(), body), client = chatHttp)

  /**
   * Queue one order. [owner] is the wallet that confirmed it (see [OrderBody]);
   * null leaves it to the session, as before.
   */
  suspend fun order(side: String, symbol: String, usdg: Double, owner: String? = null): ApiResult<OrderResult> =
    sendJson(
      "/api/orders",
      "POST",
      json.encodeToString(OrderBody.serializer(), OrderBody(side, symbol, usdg, owner)),
    )

  /** What became of one order. Polled after placing it. */
  suspend fun orderStatus(id: String): ApiResult<OrderState> =
    getJson("/api/orders?id=" + java.net.URLEncoder.encode(id, "UTF-8"))

  /** Resolve a coin by name, then (on "resolved" only) the caller places the order. [owner] as on [order]. */
  suspend fun snipe(query: String, usdg: Double, owner: String? = null): ApiResult<SnipeResult> =
    sendJson(
      "/api/snipe",
      "POST",
      json.encodeToString(SnipeBody.serializer(), SnipeBody(query, usdg, owner)),
    )

  suspend fun selftest(): ApiResult<OrderResult> = sendJson("/api/selftest", "POST", null)
  suspend fun selftestStatus(): ApiResult<JsonElement> = getJson("/api/selftest")

  /** Practice book only. The worker refuses this outright on the live rail. */
  suspend fun paperReset(): ApiResult<OrderResult> = sendJson("/api/paper-reset", "POST", null)

  suspend fun models(): ApiResult<JsonElement> = sendJson("/api/models", "POST", "{}")

  // ── likes and follows ─────────────────────────────────────────────────────

  /**
   * ONE TOGGLE, ONE ROUTE, in both cases: `on: false` is the undo.
   *
   * The bodies are ENCODED, not interpolated. A post id is a hex string and a
   * slug is shape-checked, but the two write paths that build JSON by hand were
   * also the two whose key names were wrong, and a serializer cannot get a key
   * name wrong twice.
   *
   * A 404 FROM EITHER MEANS SELF-HOSTED, not an error and not a signed-out
   * reader: one operator against one settings file has nobody for a like to be
   * attributed to and no agent to wire in. Social.kt reads the status for that.
   */
  suspend fun likes(): ApiResult<LikesView> = getJson("/api/likes")

  suspend fun like(postId: String, on: Boolean): ApiResult<LikesView> =
    sendJson("/api/likes", "POST", json.encodeToString(LikeBody.serializer(), LikeBody(postId, on)))

  suspend fun following(): ApiResult<FollowView> = getJson("/api/follow")

  suspend fun follow(target: String, on: Boolean): ApiResult<FollowView> =
    sendJson("/api/follow", "POST", json.encodeToString(FollowBody.serializer(), FollowBody(target, on)))

  /**
   * THE KILL SWITCH. Removes the grant, which stands the worker down.
   *
   * Kept beside the reads rather than hidden, because a stop control that is
   * hard to find is not a stop control.
   */
  suspend fun revokeGrant(): ApiResult<JsonElement> = sendJson("/api/grants", "DELETE", null)
}
