/**
 * Regenerate docs/mcp/tools.md from the live MCP catalogue:
 *
 *   npx tsx scripts/mcp-tools-doc.ts
 *
 * web/src/mcp/catalog.test.ts fails when a tool is missing from the file, so a
 * new tool cannot ship undocumented.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { ALL_TOOLS } from "../web/src/mcp/tools";
import { ALL_RESOURCES } from "../web/src/mcp/resources-catalog";
import { SCOPES, scopeFor } from "../web/src/mcp/scopes";
import { PROMPT_NAMES } from "../web/src/mcp/prompts";

const lines: string[] = [];
lines.push("# Merrymen MCP: tools, resources and scopes", "");
lines.push("_Generated by `scripts/mcp-tools-doc.ts` from the live catalogue. Do not edit by hand._", "");
lines.push("A connection only sees the tools its granted scopes allow, and every call is re-checked on the server. Annotations (read-only, destructive, open-world) help your client decide when to ask you; they are not what enforces access.", "");
lines.push("On the limited endpoint listed in Claude's connector directory (`/mcp/directory`), the tools that need `trade:propose`, `drafts:write`, `social:write` or `staff:diagnostics` are not listed, and tool descriptions leave out their pointers to other tools (the descriptions below are the full server's).", "");

lines.push("## Scopes", "", "| Scope | Level | Starts ticked | Allows |", "|---|---|---|---|");
for (const s of SCOPES) {
  if (s.level === "staff") continue;
  lines.push(`| \`${s.id}\` | ${s.level} | ${s.defaultOn ? "yes" : "no"} | ${s.title}. ${s.detail} |`);
}
lines.push("", "`staff:diagnostics` is never advertised; it is offered only to Merrymen operators on an allowlist and re-checked on every call.", "");

const byScope = new Map<string, typeof ALL_TOOLS[number][]>();
for (const t of ALL_TOOLS) {
  const scope = t.anyOf?.length ? t.anyOf.map((c) => scopeFor(c)).join(" or ") : scopeFor(t.capability);
  const list = byScope.get(scope) ?? [];
  list.push(t);
  byScope.set(scope, list);
}

lines.push("## Tools", "");
for (const [scope, tools] of byScope) {
  lines.push(`### Needs \`${scope.replace(/ or /g, "` or `")}\``, "", "| Tool | What it does | Kind |", "|---|---|---|");
  for (const t of tools) {
    const a = t.annotations;
    const kind = a.readOnlyHint ? "read-only" : a.destructiveHint ? "writes (destructive)" : "writes";
    const world = a.openWorldHint ? ", reaches the chain or a market provider" : "";
    lines.push(`| \`${t.name}\` | ${t.description.replace(/\|/g, "\\|").replace(/\n/g, " ")} | ${kind}${world} |`);
  }
  lines.push("");
}

lines.push("## Resources", "", "| URI | Name | Needs |", "|---|---|---|");
for (const r of ALL_RESOURCES) lines.push(`| \`${r.uri}\` | ${r.title} | ${r.capability ? `\`${scopeFor(r.capability)}\`` : "any connection"} |`);
lines.push("", "Resource URIs are names, not capabilities: reading one re-checks ownership exactly like the matching tool.", "");

lines.push("## Prompts", "", "Optional workflow templates (they carry no permissions): " + PROMPT_NAMES.map((n) => `\`${n}\``).join(", ") + ".", "");

writeFileSync(path.join(process.cwd(), "docs", "mcp", "tools.md"), `${lines.join("\n")}\n`);
console.log(`wrote docs/mcp/tools.md: ${ALL_TOOLS.length} tools, ${ALL_RESOURCES.length} resources`);
