/**
 * The X-posting tables against a real (in-memory) sqlite, plus the Postgres
 * translation of every statement the store sends — the room's store.test.ts
 * discipline, because sqlite cannot see a Postgres-only failure.
 */
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { translateQuery, translateSchema, wrapSqlite, type Db } from "../db";
import {
  XPOST_SCHEMA,
  cancelPost,
  cancelScheduled,
  claimPost,
  claimSpan,
  deferPost,
  deleteAccount,
  duePosts,
  ensureXpostSchema,
  failInterrupted,
  getAccount,
  introPostsOf,
  keyStatus,
  lastOutAt,
  markFailed,
  markPosted,
  markRevoked,
  ownerCancel,
  postingAccounts,
  postsOf,
  postsOfXUser,
  prunePending,
  putPending,
  readMeta,
  readTokens,
  recentBodies,
  releaseSpan,
  reschedulePost,
  returnAllowance,
  schedulePost,
  setPosting,
  skipScheduled,
  swapTokens,
  takeAllowance,
  takePending,
  upsertAccount,
  writeMeta,
  type NewPost,
  type TokenSetPlain,
} from "./store";

const OWNER_A = `0x${"AA".repeat(20)}`;
const OWNER_B = `0x${"bb".repeat(20)}`;
const DEK = randomBytes(32);

async function open(t: { after(fn: () => void): void }): Promise<{ db: Db; raw: DatabaseSync }> {
  const raw = new DatabaseSync(":memory:");
  t.after(() => raw.close());
  const db = wrapSqlite(raw);
  await ensureXpostSchema(db, "sqlite");
  return { db, raw };
}

const TOKENS: TokenSetPlain = {
  accessToken: "access-token-secret-1",
  refreshToken: "refresh-token-secret-1",
  accessExpiresAtMs: 10_000,
  scope: "tweet.read tweet.write users.read offline.access",
};

function post(over: Partial<NewPost> = {}): NewPost {
  return {
    tenant: OWNER_A,
    xUserId: "111",
    kind: "casual",
    dedupeKey: `casual:${OWNER_A.toLowerCase()}:2026-09-28`,
    body: "thinking about how quiet markets feel on a sunday",
    dueAtMs: 1_000,
    nowMs: 500,
    ...over,
  };
}

// ── schema ──────────────────────────────────────────────────────────────────

test("the schema is idempotent and memoised per Db", async (t) => {
  const { db } = await open(t);
  assert.equal(ensureXpostSchema(db, "sqlite"), ensureXpostSchema(db, "sqlite"));
  await db.exec(XPOST_SCHEMA);
});

test("the DDL translates to Postgres cleanly", () => {
  const pg = translateSchema(XPOST_SCHEMA);
  assert.match(pg, /id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.doesNotMatch(pg, /\bINTEGER\b/);
  assert.doesNotMatch(pg, /AUTOINCREMENT/);
  // translateSchema rewrites blind and `exec` never renumbers: no quote or
  // placeholder may hide in a comment, and no placeholder anywhere.
  const comments = [...XPOST_SCHEMA.matchAll(/--[^\n]*/g)].map((m) => m[0]).join("\n");
  assert.doesNotMatch(comments, /['?]/);
  assert.doesNotMatch(XPOST_SCHEMA, /\?/);
});

// ── pending connects ────────────────────────────────────────────────────────

test("a pending connect is single use, expires, and stores neither the state nor the verifier in the clear", async (t) => {
  const { db, raw } = await open(t);
  await putPending(db, DEK, { state: "w.state-one", tenant: OWNER_A, verifier: "verifier-plain-text", redirectUri: "https://app.test/connect/x", expiresAtMs: 2_000 });
  const stored = JSON.stringify(raw.prepare("SELECT * FROM xpost_pending").all());
  assert.ok(!stored.includes("w.state-one"), "the state is stored hashed");
  assert.ok(!stored.includes("verifier-plain-text"), "the verifier is sealed");

  const first = await takePending(db, DEK, "w.state-one", 1_000);
  assert.deepEqual(first, { tenant: OWNER_A.toLowerCase(), verifier: "verifier-plain-text", redirectUri: "https://app.test/connect/x" });
  assert.equal(await takePending(db, DEK, "w.state-one", 1_000), null, "spent");

  await putPending(db, DEK, { state: "w.state-two", tenant: OWNER_A, verifier: "v2", redirectUri: "https://app.test/connect/x", expiresAtMs: 2_000 });
  assert.equal(await takePending(db, DEK, "w.state-two", 2_000), null, "expired at its expiry");
  assert.equal(await takePending(db, DEK, "w.state-two", 1_000), null, "and deleted, not kept for later");

  await putPending(db, DEK, { state: "w.old", tenant: OWNER_A, verifier: "v", redirectUri: "https://app.test/connect/x", expiresAtMs: 100 });
  assert.equal(await prunePending(db, 1_000), 1);
});

// ── accounts ────────────────────────────────────────────────────────────────

test("tokens are sealed at rest and read back whole", async (t) => {
  const { db, raw } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  const stored = JSON.stringify(raw.prepare("SELECT * FROM xpost_accounts").all());
  assert.ok(!stored.includes(TOKENS.accessToken));
  assert.ok(!stored.includes(TOKENS.refreshToken!));
  const tokens = await readTokens(db, DEK, OWNER_A);
  assert.equal(tokens?.accessToken, TOKENS.accessToken);
  assert.equal(tokens?.refreshToken, TOKENS.refreshToken);
  assert.equal(tokens?.xUserId, "111");
  // A different DEK cannot open them — and says so, rather than handing back garbage.
  await assert.rejects(readTokens(db, randomBytes(32), OWNER_A));
});

test("posting is on only for the account the owner confirmed", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  let a = await getAccount(db, OWNER_A);
  assert.equal(a?.posting, false, "connecting is not consent");

  assert.equal(await setPosting(db, OWNER_A, { enabled: true, xUserId: "999" }, 2), false, "a warning that named another account is not consent");
  assert.equal((await getAccount(db, OWNER_A))?.posting, false);

  assert.equal(await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 3), true);
  a = await getAccount(db, OWNER_A);
  assert.equal(a?.posting, true);
  assert.equal(a?.consentAtMs, 3);
  assert.equal(a?.consentXUserId, "111");
  assert.deepEqual((await postingAccounts(db, [OWNER_A, OWNER_B])).map((x) => x.tenant), [OWNER_A.toLowerCase()]);

  // Reconnecting the SAME account keeps the switch.
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_renamed", tokens: TOKENS, nowMs: 4 });
  assert.equal((await getAccount(db, OWNER_A))?.posting, true);
  assert.equal((await getAccount(db, OWNER_A))?.username, "robin_renamed");

  // A DIFFERENT account clears it and cancels what was drafted for the old one.
  await schedulePost(db, post());
  const r = await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "222", username: "someone_else", tokens: TOKENS, nowMs: 5 });
  assert.equal(r.changedAccount, true);
  a = await getAccount(db, OWNER_A);
  assert.equal(a?.posting, false);
  assert.equal(a?.consentXUserId, null);
  assert.equal(await keyStatus(db, post().dedupeKey), "cancelled");
  assert.deepEqual(await postingAccounts(db, [OWNER_A]), []);
});

test("turning posting off cancels every draft; a revoked connection cannot post", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 2);
  await schedulePost(db, post());
  assert.equal(await setPosting(db, OWNER_A, { enabled: false }, 3), true);
  assert.equal(await keyStatus(db, post().dedupeKey), "cancelled");

  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 4);
  const v = (await getAccount(db, OWNER_A))!.version;
  assert.equal(await markRevoked(db, OWNER_A, v + 5, 5), false, "only over the version that failed");
  assert.equal(await markRevoked(db, OWNER_A, v, 5), true);
  const a = await getAccount(db, OWNER_A);
  assert.equal(a?.status, "revoked");
  assert.equal(a?.posting, false);
  assert.equal(await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 6), false, "a revoked connection cannot be switched on");
});

test("a rotated token pair is written only over the version it came from", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  const before = await readTokens(db, DEK, OWNER_A);
  const next: TokenSetPlain = { ...TOKENS, accessToken: "access-2", refreshToken: "refresh-2", accessExpiresAtMs: 20_000 };
  assert.equal(await swapTokens(db, DEK, OWNER_A, before!.version, next, 2), true);
  assert.equal(await swapTokens(db, DEK, OWNER_A, before!.version, { ...next, accessToken: "access-3" }, 3), false, "a stale version loses");
  const after = await readTokens(db, DEK, OWNER_A);
  assert.equal(after?.accessToken, "access-2");
  assert.equal(after?.refreshToken, "refresh-2");
  assert.equal(after?.version, before!.version + 1);
});

test("disconnecting hands back the tokens to revoke and forgets them", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  await schedulePost(db, post());
  const gone = await deleteAccount(db, DEK, OWNER_A, 2);
  assert.deepEqual(gone, { accessToken: TOKENS.accessToken, refreshToken: TOKENS.refreshToken });
  assert.equal(await getAccount(db, OWNER_A), null);
  assert.equal(await keyStatus(db, post().dedupeKey), "cancelled");
  assert.equal(await deleteAccount(db, DEK, OWNER_A, 3), null);
});

// ── posts ───────────────────────────────────────────────────────────────────

test("a dedupe key is written once, whether it was posted or deliberately not", async (t) => {
  const { db } = await open(t);
  const id = await schedulePost(db, post());
  assert.ok(typeof id === "number" && id > 0);
  assert.equal(await schedulePost(db, post({ body: "a different draft" })), null);
  assert.equal(await schedulePost(db, post({ dedupeKey: "buy:d1", kind: "buy", status: "skipped", reason: "gate:has-digits" })) !== null, true);
  assert.equal(await keyStatus(db, "buy:d1"), "skipped");
  assert.equal(await keyStatus(db, "buy:never"), null);
  await assert.rejects(schedulePost(db, post({ dedupeKey: "" })));
});

test("a post is claimed by exactly one sender and never sent twice", async (t) => {
  const { db } = await open(t);
  const id = (await schedulePost(db, post()))!;
  assert.deepEqual((await duePosts(db, [OWNER_A], 999)).map((p) => p.id), [], "not yet due");
  assert.deepEqual((await duePosts(db, [OWNER_A], 1_000)).map((p) => p.id), [id]);
  assert.deepEqual(await duePosts(db, [OWNER_B], 1_000), [], "only the roster's owners");

  assert.equal(await claimPost(db, id, 1_001), true);
  assert.equal(await claimPost(db, id, 1_002), false, "the second claim loses");
  assert.deepEqual(await duePosts(db, [OWNER_A], 5_000), [], "a claimed post is not due again");

  await markPosted(db, id, "1840000000000000001", 1_003);
  const [p] = await postsOf(db, OWNER_A, 0);
  assert.equal(p?.status, "posted");
  assert.equal(p?.tweetId, "1840000000000000001");
  assert.equal(p?.sentAtMs, 1_003);
});

test("a rate-limited post goes back to scheduled; a failure is final", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 400);
  const id = (await schedulePost(db, post()))!;
  await claimPost(db, id, 1_001);
  assert.equal(await reschedulePost(db, id, 9_000, 1_002), true);
  assert.deepEqual((await duePosts(db, [OWNER_A], 9_000)).map((p) => p.id), [id]);
  await claimPost(db, id, 9_001);
  await markFailed(db, id, "uncertain", 9_002);
  assert.equal(await claimPost(db, id, 9_003), false, "failed is final");
  assert.equal((await postsOf(db, OWNER_A, 0))[0]?.reason, "uncertain");
});

test("a post in flight when its account stopped posting is cancelled, never put back to scheduled", async (t) => {
  const cases: [string, (db: Db) => Promise<unknown>][] = [
    ["switched off", (db) => setPosting(db, OWNER_A, { enabled: false }, 1_010)],
    ["switched off and on again before the reschedule", async (db) => {
      await setPosting(db, OWNER_A, { enabled: false }, 1_010);
      await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 1_011);
    }],
    ["disconnected", (db) => deleteAccount(db, DEK, OWNER_A, 1_010)],
    ["revoked", async (db) => markRevoked(db, OWNER_A, (await getAccount(db, OWNER_A))!.version, 1_010)],
    ["another X account connected", (db) => upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "222", username: "someone_else", tokens: TOKENS, nowMs: 1_010 })],
  ];
  for (const [label, change] of cases) {
    const { db } = await open(t);
    await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
    await setPosting(db, OWNER_A, { enabled: true, xUserId: "111" }, 400);
    const id = (await schedulePost(db, post()))!;
    assert.equal(await claimPost(db, id, 1_001), true);
    await change(db);
    assert.equal(await keyStatus(db, post().dedupeKey), "sending", `${label}: the web cancels only scheduled rows`);
    assert.equal(await reschedulePost(db, id, 9_000, 1_020), false, label);
    const [p] = await postsOf(db, OWNER_A, 0);
    assert.equal(p?.status, "cancelled", label);
    assert.equal(p?.reason, "account-off", label);
    assert.deepEqual(await duePosts(db, [OWNER_A], 9_000), [], `${label}: nothing to send later`);
  }
});

test("a claim that outlived its process fails as interrupted, never resent", async (t) => {
  const { db } = await open(t);
  const id = (await schedulePost(db, post()))!;
  await claimPost(db, id, 1_000);
  assert.equal(await failInterrupted(db, 1_000, 2_000), 0, "a live claim is left alone");
  assert.equal(await failInterrupted(db, 1_001, 2_000), 1);
  const [p] = await postsOf(db, OWNER_A, 0);
  assert.equal(p?.status, "failed");
  assert.equal(p?.reason, "interrupted");
});

test("the owner can skip only their own post, and only while it is scheduled", async (t) => {
  const { db } = await open(t);
  const id = (await schedulePost(db, post()))!;
  assert.equal(await ownerCancel(db, OWNER_B, id, 2), false, "another owner's post");
  assert.equal(await ownerCancel(db, OWNER_A, id, 2), true);
  assert.equal(await ownerCancel(db, OWNER_A, id, 3), false, "already cancelled");

  const other = (await schedulePost(db, post({ dedupeKey: "buy:d2", kind: "buy" })))!;
  await claimPost(db, other, 4);
  assert.equal(await ownerCancel(db, OWNER_A, other, 5), false, "a claimed post cannot be half-skipped");
  assert.equal(await skipScheduled(db, other, "stale", 5), false);
});

test("the orchestrator cancels a scheduled post whose account moved on, and nothing already claimed", async (t) => {
  const { db } = await open(t);
  const id = (await schedulePost(db, post()))!;
  assert.equal(await cancelPost(db, id, "account-off", 2), true);
  assert.equal(await keyStatus(db, post().dedupeKey), "cancelled");
  assert.equal((await postsOf(db, OWNER_A, 0))[0]?.reason, "account-off");
  assert.equal(await cancelPost(db, id, "account-off", 3), false, "already cancelled");
  const claimed = (await schedulePost(db, post({ dedupeKey: "buy:d3", kind: "buy" })))!;
  await claimPost(db, claimed, 4);
  assert.equal(await cancelPost(db, claimed, "account-gone", 5), false, "a claimed post is the sender's to finish");
});

test("one X account's posts, from every owner posting on it, newest first", async (t) => {
  const { db } = await open(t);
  await schedulePost(db, post({ dedupeKey: "a-old", nowMs: 5 }));
  await schedulePost(db, post({ dedupeKey: "a", nowMs: 10 }));
  await schedulePost(db, post({ dedupeKey: "b", tenant: OWNER_B, nowMs: 20 }));
  await schedulePost(db, post({ dedupeKey: "a-other-account", xUserId: "222", nowMs: 30 }));
  assert.deepEqual((await postsOfXUser(db, "111", 10)).map((p) => [p.dedupeKey, p.tenant]), [
    ["b", OWNER_B],
    ["a", OWNER_A.toLowerCase()],
  ]);
});

test("when an X account last posted, from any owner, what went out or may have; never a hello", async (t) => {
  const { db } = await open(t);
  assert.equal(await lastOutAt(db, "111", 0), null);
  const out = async (key: string, over: Partial<NewPost>, end: (id: number) => Promise<unknown>) => {
    const id = (await schedulePost(db, post({ dedupeKey: key, ...over })))!;
    await claimPost(db, id, over.nowMs ?? 500);
    await end(id);
  };
  await out("hello", { kind: "intro", nowMs: 100 }, (id) => markPosted(db, id, "1", 9_000));
  assert.equal(await lastOutAt(db, "111", 0), null, "a hello is exempt");
  await out("a", { nowMs: 100 }, (id) => markPosted(db, id, "2", 1_000));
  await out("b", { tenant: OWNER_B, nowMs: 200 }, (id) => markPosted(db, id, "3", 2_000));
  assert.equal(await lastOutAt(db, "111", 0), 2_000, "the other owner's post on the same X account");
  await out("maybe", { nowMs: 300 }, (id) => markFailed(db, id, "uncertain", 3_000));
  assert.equal(await lastOutAt(db, "111", 0), 3_000, "an uncertain post may be on the timeline");
  await out("refused", { nowMs: 400 }, (id) => markFailed(db, id, "forbidden", 4_000));
  await schedulePost(db, post({ dedupeKey: "waiting", nowMs: 400, dueAtMs: 5_000 }));
  assert.equal(await lastOutAt(db, "111", 0), 3_000, "X refused it, and a draft is not out");
  assert.equal(await lastOutAt(db, "222", 0), null);
  assert.equal(await lastOutAt(db, "111", 250), 3_000, "only posts drafted since");
});

test("due posts page on from the last row seen, by due time then id", async (t) => {
  const { db } = await open(t);
  const ids: number[] = [];
  for (const [key, due] of [["p1", 100], ["p2", 100], ["p3", 200], ["p4", 300], ["later", 9_000]] as const) {
    ids.push((await schedulePost(db, post({ dedupeKey: key, dueAtMs: due })))!);
  }
  const first = await duePosts(db, [OWNER_A], 1_000, 2);
  assert.deepEqual(first.map((p) => p.dedupeKey), ["p1", "p2"]);
  const last = first[first.length - 1]!;
  const second = await duePosts(db, [OWNER_A], 1_000, 2, { dueAtMs: last.dueAtMs, id: last.id });
  assert.deepEqual(second.map((p) => p.dedupeKey), ["p3", "p4"]);
  assert.deepEqual(await duePosts(db, [OWNER_A], 1_000, 2, { dueAtMs: 300, id: ids[3]! }), [], "nothing due past the last");
  assert.deepEqual((await duePosts(db, [OWNER_A], 1_000, 5, { dueAtMs: 100, id: ids[0]! })).map((p) => p.dedupeKey), ["p2", "p3", "p4"], "a tie on due time goes by id");
});

test("a scheduled post can be moved later; a claimed one cannot", async (t) => {
  const { db } = await open(t);
  const id = (await schedulePost(db, post()))!;
  assert.equal(await deferPost(db, id, 9_000, 600), true);
  assert.deepEqual(await duePosts(db, [OWNER_A], 8_999), []);
  assert.equal((await duePosts(db, [OWNER_A], 9_000))[0]?.id, id);
  await claimPost(db, id, 9_001);
  assert.equal(await deferPost(db, id, 20_000, 9_002), false);
});

test("every intro one owner wrote for one X account, any status and any age, oldest first", async (t) => {
  const { db } = await open(t);
  const base = `intro:${OWNER_A.toLowerCase()}:111`;
  await schedulePost(db, post({ kind: "intro", dedupeKey: base, nowMs: 10, status: "skipped", reason: "template:echo" }));
  await schedulePost(db, post({ kind: "intro", dedupeKey: `${base}:1`, nowMs: 20 }));
  await schedulePost(db, post({ kind: "intro", dedupeKey: `intro:${OWNER_A.toLowerCase()}:222`, xUserId: "222", nowMs: 30 }));
  await schedulePost(db, post({ kind: "intro", dedupeKey: `intro:${OWNER_B}:111`, tenant: OWNER_B, nowMs: 40 }));
  await schedulePost(db, post({ kind: "casual", nowMs: 50 }));
  assert.deepEqual((await introPostsOf(db, OWNER_A, "111")).map((p) => [p.dedupeKey, p.status]), [
    [base, "skipped"],
    [`${base}:1`, "scheduled"],
  ]);
});

test("recent bodies: one account's, or the fleet's, never the ones that did not go out", async (t) => {
  const { db } = await open(t);
  await schedulePost(db, post({ dedupeKey: "a1", body: "one", nowMs: 10 }));
  await schedulePost(db, post({ dedupeKey: "b1", tenant: OWNER_B, body: "two", nowMs: 20 }));
  await schedulePost(db, post({ dedupeKey: "a2", body: "three", nowMs: 30, status: "skipped" }));
  const cancelled = (await schedulePost(db, post({ dedupeKey: "a3", body: "four", nowMs: 40 })))!;
  await ownerCancel(db, OWNER_A, cancelled, 41);
  assert.deepEqual(await recentBodies(db, { tenant: OWNER_A, sinceMs: 0, limit: 10 }), ["one"]);
  assert.deepEqual(await recentBodies(db, { tenant: null, sinceMs: 0, limit: 10 }), ["two", "one"]);
  assert.deepEqual(await recentBodies(db, { tenant: null, sinceMs: 15, limit: 10 }), ["two"]);
  assert.equal(await cancelScheduled(db, OWNER_B, 50, "turned-off"), 1);
});

test("an allowance is taken atomically and stops at its limit", async (t) => {
  const { db } = await open(t);
  assert.equal(await takeAllowance(db, "llm:2026-09-28", 2, 1), true);
  assert.equal(await takeAllowance(db, "llm:2026-09-28", 2, 2), true);
  assert.equal(await takeAllowance(db, "llm:2026-09-28", 2, 3), false);
  assert.equal(await takeAllowance(db, "llm:2026-09-29", 2, 4), true, "a new day is a new counter");
  assert.equal(await takeAllowance(db, "zero", 0, 5), false);
  assert.equal((await readMeta(db, "llm:2026-09-28"))?.n, 2);
  await returnAllowance(db, "llm:2026-09-28", 3);
  assert.equal(await takeAllowance(db, "llm:2026-09-28", 2, 3), true, "one given back can be taken again");
  for (let i = 0; i < 4; i++) await returnAllowance(db, "llm:2026-09-29", 4);
  assert.equal((await readMeta(db, "llm:2026-09-29"))?.n, 0, "never below zero");
  await returnAllowance(db, "never-taken", 4);
  assert.equal(await readMeta(db, "never-taken"), null);
  await writeMeta(db, "pause", "123", 6);
  await writeMeta(db, "pause", "456", 7);
  assert.equal((await readMeta(db, "pause"))?.v, "456");
});

// ── what Postgres would receive ─────────────────────────────────────────────

interface Sent {
  sql: string;
  params: unknown[];
}

function recording(inner: Db, sent: Sent[]): Db {
  return {
    prepare(sql) {
      const stmt = inner.prepare(sql);
      const note = (params: unknown[]) => sent.push({ sql, params });
      return {
        run: (...p) => (note(p), stmt.run(...p)),
        get: (...p) => (note(p), stmt.get(...p)),
        all: (...p) => (note(p), stmt.all(...p)),
      };
    },
    exec: (sql) => inner.exec(sql),
    tx: (fn) => inner.tx((scoped) => fn(recording(scoped, sent))),
  };
}

test("every statement the store sends translates to Postgres with matching, bindable parameters", async (t) => {
  const { db: base } = await open(t);
  const sent: Sent[] = [];
  const db = recording(base, sent);

  // Deliberately untidy numbers: fractional milliseconds must never reach a BIGINT.
  await putPending(db, DEK, { state: "w.s", tenant: OWNER_A, verifier: "v", redirectUri: "https://a.test/connect/x", expiresAtMs: 2_000.5 });
  await takePending(db, DEK, "w.s", 1_000.2);
  await prunePending(db, 1_000.9);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "r", tokens: { ...TOKENS, accessExpiresAtMs: 1.5 }, nowMs: 1.5 });
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "222", username: "r", tokens: TOKENS, nowMs: 2.5 });
  await getAccount(db, OWNER_A);
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "222" }, 3.5);
  await postingAccounts(db, [OWNER_A, OWNER_B]);
  await readTokens(db, DEK, OWNER_A);
  await swapTokens(db, DEK, OWNER_A, 2, TOKENS, 4.5);
  const id = (await schedulePost(db, post({ dueAtMs: 5.5, nowMs: 5.5 })))!;
  await keyStatus(db, post().dedupeKey);
  await duePosts(db, [OWNER_A], 6.5, 10.5);
  await duePosts(db, [OWNER_A], 6.5, 10.5, { dueAtMs: 1.5, id: 1 });
  await claimPost(db, id, 7.5);
  await reschedulePost(db, id, 8.5, 8.5);
  await claimPost(db, id, 9.5);
  await markPosted(db, id, "1", 10.5);
  await markFailed(db, id, "x", 11.5);
  await skipScheduled(db, id, "stale", 11.5);
  await cancelPost(db, id, "account-off", 12.5);
  await ownerCancel(db, OWNER_A, id, 12.5);
  await failInterrupted(db, 13.5, 13.5);
  await postsOf(db, OWNER_A, 0.5, 20.5);
  await introPostsOf(db, OWNER_A, "111");
  await postsOfXUser(db, "111", 0.5, 20.5);
  await lastOutAt(db, "111", 0.5);
  await deferPost(db, id, 21.5, 21.5);
  await recentBodies(db, { tenant: OWNER_A, sinceMs: 0.5, limit: 5.5 });
  await recentBodies(db, { tenant: null, sinceMs: 0.5, limit: 5.5 });
  await returnAllowance(db, "k", 14.7);
  await takeAllowance(db, "k", 3.5, 14.5);
  const span = await claimSpan(db, "gap:111", 20.5, 10.5);
  await claimSpan(db, "gap:111", 21.5, 10.5);
  if (span.ok) await releaseSpan(db, "gap:111", 20.5, span.prev, 22.5);
  await releaseSpan(db, "gap:111", 20.5, 7.5, 22.5);
  await readMeta(db, "k");
  await writeMeta(db, "k", "v", 15.5);
  await setPosting(db, OWNER_A, { enabled: false }, 16.5);
  await markRevoked(db, OWNER_A, 3, 17.5);
  await cancelScheduled(db, OWNER_A, 18.5, "turned-off");
  await deleteAccount(db, DEK, OWNER_A, 19.5);

  assert.ok(sent.length >= 30);
  for (const { sql, params } of sent) {
    const pg = translateQuery(sql);
    const unquoted = pg.replace(/'[^']*'/g, "''");
    assert.ok(!unquoted.includes("?"), `a placeholder survived translation: ${pg}`);
    const numbers = [...unquoted.matchAll(/\$(\d+)/g)].map((m) => Number(m[1]));
    const highest = numbers.length ? Math.max(...numbers) : 0;
    assert.equal(highest, params.length, `placeholder count vs parameters: ${pg}`);
    for (let n = 1; n <= highest; n++) assert.ok(numbers.includes(n), `$${n} missing: ${pg}`);
    assert.ok(!/INSERT\s+OR/i.test(pg), "INSERT OR IGNORE cannot carry RETURNING on Postgres");
    assert.ok(!/\bAS\s+[a-z_]*[A-Z]/.test(pg), `a camelCase alias would be folded by Postgres: ${pg}`);
    if (/ON CONFLICT/i.test(pg) && /DO UPDATE SET/i.test(pg)) {
      const assignments = pg.split(/DO UPDATE SET/i)[1]!.split(/\bWHERE\b(?![^()]*\))|\bRETURNING\b/i)[0]!;
      for (const part of assignments.split(/,(?![^()]*\))/)) {
        const rhs = part.split("=").slice(1).join("=").trim();
        assert.ok(/^(excluded\.|CASE WHEN xpost_accounts\.|xpost_meta\.)/.test(rhs), `bare right-hand side in an upsert: ${part.trim()}`);
      }
    }
    for (const p of params) {
      const bindable = p === null || typeof p === "string" || (typeof p === "number" && Number.isSafeInteger(p));
      assert.ok(bindable, `pg cannot bind ${String(p)} (${typeof p}) in: ${pg}`);
    }
  }
});

test("the zone the owner consented from is kept, and a consent without one keeps the last", async (t) => {
  const { db } = await open(t);
  await upsertAccount(db, DEK, { tenant: OWNER_A, xUserId: "111", username: "robin_trades", tokens: TOKENS, nowMs: 1 });
  assert.equal((await getAccount(db, OWNER_A))?.tz, null);
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111", tz: "Europe/Paris" }, 2);
  assert.equal((await getAccount(db, OWNER_A))?.tz, "Europe/Paris");
  await setPosting(db, OWNER_A, { enabled: false }, 3);
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111", tz: null }, 4);
  assert.equal((await getAccount(db, OWNER_A))?.tz, "Europe/Paris", "no zone this time is not a new zone");
  await setPosting(db, OWNER_A, { enabled: true, xUserId: "111", tz: "Asia/Tokyo" }, 5);
  assert.equal((await getAccount(db, OWNER_A))?.tz, "Asia/Tokyo");
});

test("a span of an X account's clock is claimed by exactly one of two racing claimants, and given back only if still ours", async (t) => {
  const { db } = await open(t);
  const GAP = 3 * 60 * 60_000;
  // Two replicas claim the same instant: one wins, the other learns when the span began.
  const [a, b] = await Promise.all([claimSpan(db, "gap:111", 1_000_000, GAP), claimSpan(db, "gap:111", 1_000_000, GAP)]);
  assert.deepEqual([a.ok, b.ok].sort(), [false, true]);
  const lost = a.ok ? b : a;
  assert.deepEqual(lost, { ok: false, lastAtMs: 1_000_000 });
  // Inside the span: refused. At its end: the next claim wins, and remembers the one before it.
  assert.equal((await claimSpan(db, "gap:111", 1_000_000 + GAP - 1, GAP)).ok, false);
  const next = await claimSpan(db, "gap:111", 1_000_000 + GAP, GAP);
  assert.deepEqual(next, { ok: true, prev: 1_000_000 });
  // Another X account's clock is its own.
  assert.equal((await claimSpan(db, "gap:222", 1_000_000 + 1, GAP)).ok, true);
  // Given back: the previous span is restored, so a post that never went out does not hold the account.
  await releaseSpan(db, "gap:111", 1_000_000 + GAP, 1_000_000, 1_000_000 + GAP + 5);
  assert.equal((await readMeta(db, "gap:111"))?.n, 1_000_000);
  // A release that is no longer ours changes nothing: a later claim by another replica stands.
  await claimSpan(db, "gap:111", 1_000_000 + 2 * GAP, GAP);
  await releaseSpan(db, "gap:111", 1_000_000 + GAP, 1_000_000, 1_000_000 + 2 * GAP + 5);
  assert.equal((await readMeta(db, "gap:111"))?.n, 1_000_000 + 2 * GAP);
  // The first claim on a clock, given back, leaves no row.
  const first = await claimSpan(db, "fold:111:pepe", 5, GAP);
  assert.deepEqual(first, { ok: true, prev: null });
  await releaseSpan(db, "fold:111:pepe", 5, null, 6);
  assert.equal(await readMeta(db, "fold:111:pepe"), null);
});
