-- THE SHARED POSTGRES SCHEMA PRODUCTION RAN BEFORE THE ENERGY RELEASE.
--
-- `pg_dump --schema-only --no-owner --no-privileges` (Postgres 17.11) of a
-- database built by the boot code of commit 75995697 — the release deployed
-- when energy was merged: initStore/initPostgres and applyLedgerSchema (the
-- ledger), mirror_state and its last_stamp ALTER, tenant_telegram, the
-- agent_commands receipt ALTER, risk_periods, paper_checkpoints, the MCP and
-- group-chat schemas, announcements, tenant_settings (PgSettingsStore) and
-- grants (PgGrantStore). Comments, SET lines and the `public.` qualifier were
-- stripped so it loads into a test run's own schema.
--
-- The starting point of pg-upgrade.postgres.test.ts: every new or changed
-- statement is run against THIS, the tables as they really are, not as this
-- branch would have created them. Regenerate only for a new production
-- baseline, from that release's own boot code — never from this branch.
CREATE TABLE agent_commands (
    id text NOT NULL,
    agent_id text NOT NULL,
    kind text NOT NULL,
    created_at bigint NOT NULL,
    claimed_at bigint,
    done_at bigint,
    result text,
    args text,
    receipt text
);
CREATE TABLE agents (
    smart_account text NOT NULL,
    name text DEFAULT 'Robin'::text NOT NULL,
    owner_address text NOT NULL,
    session_key_address text NOT NULL,
    chain_id bigint NOT NULL,
    caps text NOT NULL,
    granted_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    status text DEFAULT 'armed'::text NOT NULL,
    created_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    hwm_usdg double precision DEFAULT 0 NOT NULL,
    accrued_fee_usdg double precision DEFAULT 0 NOT NULL,
    epoch bigint DEFAULT 1 NOT NULL,
    mode text,
    beat_at bigint,
    sponsor_gas bigint,
    live_blocker text,
    x_handle text,
    x_verified bigint DEFAULT 0 NOT NULL,
    contributions_known bigint,
    contributions_why text,
    gas_accounting text,
    quality_at bigint,
    hwm_withdrawn_usdg double precision DEFAULT 0 NOT NULL
);
CREATE TABLE announcements (
    announce_id text NOT NULL,
    tenant text NOT NULL,
    sent_at bigint NOT NULL
);
CREATE TABLE brain_trigger_state (
    agent_id text NOT NULL,
    state_json text NOT NULL,
    updated_at bigint NOT NULL
);
CREATE TABLE chat_turns (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    memory_ids text,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
ALTER TABLE chat_turns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chat_turns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE class_positions (
    agent_id text NOT NULL,
    token text NOT NULL,
    symbol text,
    decimals bigint DEFAULT 18 NOT NULL,
    curve text,
    quote_token text,
    first_seen bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    vault text,
    entry_tx text,
    exit_tx text,
    cost_usdg text,
    qty_raw text,
    proceeds_usdg text,
    opened_at_block text,
    state text DEFAULT 'open'::text NOT NULL,
    swept_raw text
);
CREATE TABLE cost_basis (
    agent_id text NOT NULL,
    mode text NOT NULL,
    symbol text NOT NULL,
    qty_raw text NOT NULL,
    cost_usdg text NOT NULL,
    updated_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
CREATE TABLE decisions (
    id text NOT NULL,
    agent_id text NOT NULL,
    source text NOT NULL,
    strategy text,
    provider text,
    model text,
    symbol text,
    action text,
    size_usdg double precision,
    reason text,
    dropped_rule text,
    signals_json text,
    evidence_json text,
    provenance text,
    display_name text,
    mark_usd double precision,
    mcap_usd double precision,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    hold_kind text
);
CREATE TABLE discovered_pools (
    address text NOT NULL,
    symbol text NOT NULL,
    first_seen bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    decimals bigint DEFAULT 18 NOT NULL,
    liquidity_usd double precision DEFAULT 0 NOT NULL,
    fdv_usd double precision DEFAULT 0 NOT NULL,
    pool_currency0 text,
    pool_currency1 text,
    pool_fee bigint,
    pool_tick_spacing bigint,
    pool_hooks text,
    curve text,
    quote_token text,
    pool_announced_at bigint,
    graduation_threshold text
);
CREATE TABLE equity (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    eth_wei text NOT NULL,
    cash_usdg double precision NOT NULL,
    vault_usdg double precision NOT NULL,
    equity_usdg double precision NOT NULL,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    positions_usdg double precision DEFAULT 0 NOT NULL,
    epoch bigint DEFAULT 1 NOT NULL,
    mode text
);
ALTER TABLE equity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME equity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE events (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    level text DEFAULT 'ok'::text NOT NULL,
    message text NOT NULL,
    created_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
ALTER TABLE events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE fee_accruals (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    profit_usdg double precision NOT NULL,
    fee_usdg double precision NOT NULL,
    hwm_before_usdg double precision NOT NULL,
    hwm_after_usdg double precision NOT NULL,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    epoch bigint DEFAULT 1 NOT NULL
);
ALTER TABLE fee_accruals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fee_accruals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE flows (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    direction text NOT NULL,
    amount_usdg double precision NOT NULL,
    tx_hash text,
    block_number bigint,
    source text NOT NULL,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    epoch bigint DEFAULT 1 NOT NULL,
    log_index bigint,
    chain_id bigint
);
ALTER TABLE flows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME flows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE flows_quarantine (
    original_id bigint NOT NULL,
    agent_id text NOT NULL,
    epoch bigint,
    direction text,
    amount_usdg double precision,
    tx_hash text,
    block_number bigint,
    log_index bigint,
    source text,
    at bigint,
    run_id text NOT NULL,
    quarantined_at bigint NOT NULL,
    reason text NOT NULL,
    replaced_by text
);
CREATE TABLE grants (
    tenant text NOT NULL,
    chain_id integer NOT NULL,
    grant_json jsonb NOT NULL,
    sealed_session_key text NOT NULL,
    updated_at bigint NOT NULL
);
CREATE TABLE groupchat_members (
    tenant text NOT NULL,
    tz text,
    tz_source text,
    muted bigint DEFAULT 0 NOT NULL,
    joined_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
CREATE TABLE groupchat_messages (
    id bigint NOT NULL,
    created_at_ms bigint NOT NULL,
    author_kind text NOT NULL,
    tenant text NOT NULL,
    agent_id text,
    speaker_slug text,
    speaker_name text NOT NULL,
    body text NOT NULL,
    reply_to bigint,
    kind text DEFAULT 'chat'::text NOT NULL,
    call_side text,
    call_symbol text,
    call_name text,
    call_token text,
    call_paper bigint,
    call_decision_id text,
    dedupe_key text,
    hidden bigint DEFAULT 0 NOT NULL
);
ALTER TABLE groupchat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME groupchat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE groupchat_room (
    k text NOT NULL,
    v text NOT NULL,
    updated_at_ms bigint NOT NULL
);
CREATE TABLE journal (
    seq bigint NOT NULL,
    agent_id text NOT NULL,
    epoch bigint NOT NULL,
    kind text NOT NULL,
    payload_json text NOT NULL,
    prev_hash text NOT NULL,
    hash text NOT NULL,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
ALTER TABLE journal ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME journal_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE mcp_audit (
    id text NOT NULL,
    at bigint NOT NULL,
    tenant text,
    connection_id text,
    client_id text,
    action text NOT NULL,
    capability text,
    outcome text NOT NULL,
    latency_ms bigint,
    trace_id text,
    detail_json text
);
CREATE TABLE mcp_auth_requests (
    id_hash text NOT NULL,
    client_id text NOT NULL,
    redirect_uri text NOT NULL,
    code_challenge text NOT NULL,
    state text,
    scopes text NOT NULL,
    resource text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    status text NOT NULL
);
CREATE TABLE mcp_clients (
    client_id text NOT NULL,
    kind text NOT NULL,
    client_name text,
    redirect_uris text NOT NULL,
    auth_method text NOT NULL,
    secret_hash text,
    metadata_json text NOT NULL,
    created_at bigint NOT NULL,
    fetched_at bigint NOT NULL,
    expires_at bigint
);
CREATE TABLE mcp_codes (
    code_hash text NOT NULL,
    connection_id text NOT NULL,
    client_id text NOT NULL,
    redirect_uri text NOT NULL,
    code_challenge text NOT NULL,
    resource text NOT NULL,
    scopes text NOT NULL,
    family text NOT NULL,
    expires_at bigint NOT NULL,
    used_at bigint
);
CREATE TABLE mcp_connections (
    id text NOT NULL,
    tenant text NOT NULL,
    client_id text NOT NULL,
    client_name text,
    client_host text,
    kind text NOT NULL,
    scopes text NOT NULL,
    agent_slugs text NOT NULL,
    status text NOT NULL,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    last_used_at bigint,
    revoked_at bigint,
    revoked_why text,
    resource text
);
CREATE TABLE mcp_exports (
    id text NOT NULL,
    tenant text NOT NULL,
    connection_id text,
    kind text NOT NULL,
    format text NOT NULL,
    filename text NOT NULL,
    content text NOT NULL,
    bytes bigint NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL
);
CREATE TABLE mcp_jobs (
    id text NOT NULL,
    tenant text NOT NULL,
    connection_id text,
    kind text NOT NULL,
    params_json text NOT NULL,
    status text NOT NULL,
    progress double precision NOT NULL,
    result_json text,
    error_code text,
    error_message text,
    idempotency_key text,
    cancel_requested bigint NOT NULL,
    attempts bigint NOT NULL,
    created_at bigint NOT NULL,
    started_at bigint,
    finished_at bigint,
    lease_until bigint,
    deadline_at bigint NOT NULL
);
CREATE TABLE mcp_messages (
    id text NOT NULL,
    tenant text NOT NULL,
    agent_slug text NOT NULL,
    conversation_id text NOT NULL,
    connection_id text,
    request_id text NOT NULL,
    role text NOT NULL,
    content text,
    status text NOT NULL,
    error_code text,
    created_at bigint NOT NULL,
    completed_at bigint
);
CREATE TABLE mcp_proposals (
    id text NOT NULL,
    tenant text NOT NULL,
    agent_slug text,
    agent_account text,
    connection_id text,
    client_name text,
    kind text NOT NULL,
    status text NOT NULL,
    version bigint NOT NULL,
    binding_json text NOT NULL,
    binding_hash text NOT NULL,
    summary_json text NOT NULL,
    idempotency_key text,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    decided_at bigint,
    order_id text,
    result_json text
);
CREATE TABLE mcp_rate (
    bucket text NOT NULL,
    window_start bigint NOT NULL,
    hits bigint NOT NULL
);
CREATE TABLE mcp_research (
    id text NOT NULL,
    tenant text NOT NULL,
    agent_slug text NOT NULL,
    connection_id text,
    client_name text,
    title text NOT NULL,
    body text NOT NULL,
    sources_json text NOT NULL,
    tokens_json text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL
);
CREATE TABLE mcp_tokens (
    token_hash text NOT NULL,
    connection_id text NOT NULL,
    kind text NOT NULL,
    family text NOT NULL,
    scopes text NOT NULL,
    resource text NOT NULL,
    client_id text NOT NULL,
    label text,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    family_expires_at bigint NOT NULL,
    used_at bigint,
    revoked_at bigint
);
CREATE TABLE mcp_watchlist (
    tenant text NOT NULL,
    chain_id bigint NOT NULL,
    token text NOT NULL,
    symbol text,
    label text,
    note text,
    created_at bigint NOT NULL
);
CREATE TABLE mirror_state (
    tenant text NOT NULL,
    table_name text NOT NULL,
    last_id bigint DEFAULT 0 NOT NULL,
    last_stamp bigint,
    updated_at bigint DEFAULT 0 NOT NULL
);
CREATE TABLE notify_deliveries (
    id text NOT NULL,
    subscription_id text NOT NULL,
    tenant text NOT NULL,
    dedupe_key text NOT NULL,
    kind text NOT NULL,
    channel text NOT NULL,
    status text NOT NULL,
    attempts bigint NOT NULL,
    next_attempt_at bigint NOT NULL,
    last_error_code text,
    payload_json text NOT NULL,
    created_at bigint NOT NULL,
    sent_at bigint
);
CREATE TABLE notify_subscriptions (
    id text NOT NULL,
    tenant text NOT NULL,
    agent_slug text,
    channel text NOT NULL,
    kind text NOT NULL,
    params_json text NOT NULL,
    status text NOT NULL,
    connection_id text,
    cursor_json text,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    last_evaluated_at bigint
);
CREATE TABLE paper_book (
    agent_id text NOT NULL,
    cash_usdg double precision NOT NULL,
    vault_usdg double precision DEFAULT 0 NOT NULL,
    hwm_usdg double precision DEFAULT 0 NOT NULL,
    shares text DEFAULT '{}'::text NOT NULL,
    updated_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
CREATE TABLE paper_checkpoints (
    agent_id text NOT NULL,
    epoch bigint NOT NULL,
    cash_usdg double precision NOT NULL,
    vault_usdg double precision NOT NULL,
    hwm_usdg double precision NOT NULL,
    shares text NOT NULL,
    basis_json text NOT NULL,
    updated_at bigint NOT NULL
);
CREATE TABLE position_floors (
    agent_id text NOT NULL,
    mode text NOT NULL,
    symbol text NOT NULL,
    stop_bps bigint NOT NULL,
    rung text NOT NULL,
    why text NOT NULL,
    at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
CREATE TABLE positions (
    agent_id text NOT NULL,
    symbol text NOT NULL,
    token text NOT NULL,
    raw_balance text NOT NULL,
    ui_multiplier text NOT NULL,
    price_usd double precision NOT NULL,
    price_stale bigint DEFAULT 0 NOT NULL,
    value_usdg double precision NOT NULL,
    updated_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    price_source text DEFAULT 'chainlink'::text NOT NULL,
    custody text DEFAULT 'account'::text NOT NULL
);
CREATE TABLE posts (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    decision_id text NOT NULL,
    body text NOT NULL,
    created_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
ALTER TABLE posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE risk_periods (
    id text NOT NULL,
    agent_id text NOT NULL,
    started_at bigint NOT NULL,
    baseline_usdg double precision NOT NULL,
    hwm_usdg double precision NOT NULL,
    withdrawn_usdg double precision DEFAULT 0 NOT NULL,
    reason text NOT NULL
);
CREATE TABLE tenant_settings (
    tenant text NOT NULL,
    sealed text NOT NULL,
    updated_at bigint NOT NULL
);
CREATE TABLE tenant_telegram (
    tenant text NOT NULL,
    link_code text,
    owner_id bigint,
    linked_at bigint,
    updated_at bigint DEFAULT 0 NOT NULL
);
CREATE TABLE trades (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    kind text NOT NULL,
    target text NOT NULL,
    sell_token text,
    buy_token text,
    amount_usdg double precision NOT NULL,
    user_op_hash text,
    tx_hash text,
    status text NOT NULL,
    reject_rule text,
    created_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL,
    sim_quote_out text,
    sim_min_out text,
    sim_fee_tier bigint,
    sim_gas text,
    decision_id text,
    fill_side text,
    fill_symbol text,
    fill_qty_raw text,
    fill_price_usd double precision,
    realized_pnl_usdg double precision,
    basis_source text,
    order_id text,
    settlement_status text,
    gas_wei text,
    sponsored_gas_wei text,
    epoch bigint DEFAULT 1 NOT NULL,
    fill_slippage_bps bigint,
    fill_cash_usdg double precision,
    gas_usdg double precision,
    gas_units text,
    trade_fee_usdg double precision
);
ALTER TABLE trades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE trench_positions (
    agent_id text NOT NULL,
    mode text NOT NULL,
    symbol text NOT NULL,
    entry_liquidity_usd double precision NOT NULL,
    entry_sec bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint NOT NULL
);
ALTER TABLE ONLY agent_commands
    ADD CONSTRAINT agent_commands_pkey PRIMARY KEY (id);
ALTER TABLE ONLY agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (smart_account);
ALTER TABLE ONLY announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (announce_id, tenant);
ALTER TABLE ONLY brain_trigger_state
    ADD CONSTRAINT brain_trigger_state_pkey PRIMARY KEY (agent_id);
ALTER TABLE ONLY chat_turns
    ADD CONSTRAINT chat_turns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY class_positions
    ADD CONSTRAINT class_positions_pkey PRIMARY KEY (agent_id, token);
ALTER TABLE ONLY cost_basis
    ADD CONSTRAINT cost_basis_pkey PRIMARY KEY (agent_id, mode, symbol);
ALTER TABLE ONLY decisions
    ADD CONSTRAINT decisions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY discovered_pools
    ADD CONSTRAINT discovered_pools_pkey PRIMARY KEY (address);
ALTER TABLE ONLY equity
    ADD CONSTRAINT equity_pkey PRIMARY KEY (id);
ALTER TABLE ONLY events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY fee_accruals
    ADD CONSTRAINT fee_accruals_pkey PRIMARY KEY (id);
ALTER TABLE ONLY flows
    ADD CONSTRAINT flows_pkey PRIMARY KEY (id);
ALTER TABLE ONLY flows_quarantine
    ADD CONSTRAINT flows_quarantine_pkey PRIMARY KEY (run_id, original_id);
ALTER TABLE ONLY grants
    ADD CONSTRAINT grants_pkey PRIMARY KEY (tenant);
ALTER TABLE ONLY groupchat_members
    ADD CONSTRAINT groupchat_members_pkey PRIMARY KEY (tenant);
ALTER TABLE ONLY groupchat_messages
    ADD CONSTRAINT groupchat_messages_dedupe_key_key UNIQUE (dedupe_key);
ALTER TABLE ONLY groupchat_messages
    ADD CONSTRAINT groupchat_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY groupchat_room
    ADD CONSTRAINT groupchat_room_pkey PRIMARY KEY (k);
ALTER TABLE ONLY journal
    ADD CONSTRAINT journal_pkey PRIMARY KEY (seq);
ALTER TABLE ONLY mcp_audit
    ADD CONSTRAINT mcp_audit_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_auth_requests
    ADD CONSTRAINT mcp_auth_requests_pkey PRIMARY KEY (id_hash);
ALTER TABLE ONLY mcp_clients
    ADD CONSTRAINT mcp_clients_pkey PRIMARY KEY (client_id);
ALTER TABLE ONLY mcp_codes
    ADD CONSTRAINT mcp_codes_pkey PRIMARY KEY (code_hash);
ALTER TABLE ONLY mcp_connections
    ADD CONSTRAINT mcp_connections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_exports
    ADD CONSTRAINT mcp_exports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_jobs
    ADD CONSTRAINT mcp_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_messages
    ADD CONSTRAINT mcp_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_proposals
    ADD CONSTRAINT mcp_proposals_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_rate
    ADD CONSTRAINT mcp_rate_pkey PRIMARY KEY (bucket, window_start);
ALTER TABLE ONLY mcp_research
    ADD CONSTRAINT mcp_research_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mcp_tokens
    ADD CONSTRAINT mcp_tokens_pkey PRIMARY KEY (token_hash);
ALTER TABLE ONLY mcp_watchlist
    ADD CONSTRAINT mcp_watchlist_pkey PRIMARY KEY (tenant, chain_id, token);
ALTER TABLE ONLY mirror_state
    ADD CONSTRAINT mirror_state_pkey PRIMARY KEY (tenant, table_name);
ALTER TABLE ONLY notify_deliveries
    ADD CONSTRAINT notify_deliveries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY notify_subscriptions
    ADD CONSTRAINT notify_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY paper_book
    ADD CONSTRAINT paper_book_pkey PRIMARY KEY (agent_id);
ALTER TABLE ONLY paper_checkpoints
    ADD CONSTRAINT paper_checkpoints_pkey PRIMARY KEY (agent_id);
ALTER TABLE ONLY position_floors
    ADD CONSTRAINT position_floors_pkey PRIMARY KEY (agent_id, mode, symbol);
ALTER TABLE ONLY positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (agent_id, symbol);
ALTER TABLE ONLY posts
    ADD CONSTRAINT posts_decision_id_key UNIQUE (decision_id);
ALTER TABLE ONLY posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY risk_periods
    ADD CONSTRAINT risk_periods_agent_id_started_at_key UNIQUE (agent_id, started_at);
ALTER TABLE ONLY risk_periods
    ADD CONSTRAINT risk_periods_pkey PRIMARY KEY (id);
ALTER TABLE ONLY tenant_settings
    ADD CONSTRAINT tenant_settings_pkey PRIMARY KEY (tenant);
ALTER TABLE ONLY tenant_telegram
    ADD CONSTRAINT tenant_telegram_pkey PRIMARY KEY (tenant);
ALTER TABLE ONLY trades
    ADD CONSTRAINT trades_pkey PRIMARY KEY (id);
ALTER TABLE ONLY trench_positions
    ADD CONSTRAINT trench_positions_pkey PRIMARY KEY (agent_id, mode, symbol);
CREATE INDEX chat_turns_chat_time ON chat_turns USING btree (chat_id, id DESC);
CREATE INDEX class_positions_agent ON class_positions USING btree (agent_id);
CREATE INDEX decisions_agent_time ON decisions USING btree (agent_id, at DESC);
CREATE INDEX decisions_time ON decisions USING btree (at DESC);
CREATE INDEX equity_agent_time ON equity USING btree (agent_id, at DESC);
CREATE INDEX events_agent_time ON events USING btree (agent_id, created_at DESC);
CREATE INDEX fee_accruals_agent_time ON fee_accruals USING btree (agent_id, at DESC);
CREATE INDEX flows_agent_time ON flows USING btree (agent_id, at DESC);
CREATE UNIQUE INDEX flows_chain_identity ON flows USING btree (chain_id, agent_id, tx_hash, log_index) WHERE ((tx_hash IS NOT NULL) AND (log_index IS NOT NULL));
CREATE INDEX flows_quarantine_agent ON flows_quarantine USING btree (agent_id);
CREATE INDEX groupchat_messages_tenant ON groupchat_messages USING btree (tenant, id);
CREATE INDEX journal_agent_epoch ON journal USING btree (agent_id, epoch, seq);
CREATE INDEX mcp_audit_at ON mcp_audit USING btree (at);
CREATE INDEX mcp_audit_connection ON mcp_audit USING btree (connection_id, at);
CREATE INDEX mcp_audit_tenant ON mcp_audit USING btree (tenant, at);
CREATE INDEX mcp_auth_requests_expiry ON mcp_auth_requests USING btree (expires_at);
CREATE INDEX mcp_clients_kind_created ON mcp_clients USING btree (kind, created_at);
CREATE INDEX mcp_clients_kind_expiry ON mcp_clients USING btree (kind, expires_at);
CREATE INDEX mcp_codes_expiry ON mcp_codes USING btree (expires_at);
CREATE UNIQUE INDEX mcp_connections_one_active ON mcp_connections USING btree (tenant, client_id, COALESCE(resource, ''::text)) WHERE ((status = 'active'::text) AND (kind = 'oauth'::text));
CREATE INDEX mcp_connections_tenant ON mcp_connections USING btree (tenant, status);
CREATE INDEX mcp_exports_expiry ON mcp_exports USING btree (expires_at);
CREATE INDEX mcp_exports_tenant ON mcp_exports USING btree (tenant, created_at);
CREATE INDEX mcp_jobs_finished ON mcp_jobs USING btree (finished_at);
CREATE UNIQUE INDEX mcp_jobs_idempotency ON mcp_jobs USING btree (tenant, idempotency_key);
CREATE INDEX mcp_jobs_queue ON mcp_jobs USING btree (status, created_at);
CREATE INDEX mcp_jobs_tenant ON mcp_jobs USING btree (tenant, created_at);
CREATE INDEX mcp_messages_conversation ON mcp_messages USING btree (tenant, conversation_id, created_at);
CREATE INDEX mcp_messages_created ON mcp_messages USING btree (created_at);
CREATE UNIQUE INDEX mcp_messages_request ON mcp_messages USING btree (tenant, request_id, role);
CREATE UNIQUE INDEX mcp_proposals_idempotency ON mcp_proposals USING btree (tenant, idempotency_key);
CREATE INDEX mcp_proposals_tenant ON mcp_proposals USING btree (tenant, created_at);
CREATE INDEX mcp_rate_window ON mcp_rate USING btree (window_start);
CREATE INDEX mcp_research_expiry ON mcp_research USING btree (expires_at);
CREATE INDEX mcp_research_tenant ON mcp_research USING btree (tenant, created_at);
CREATE INDEX mcp_tokens_connection ON mcp_tokens USING btree (connection_id);
CREATE INDEX mcp_tokens_expiry ON mcp_tokens USING btree (expires_at);
CREATE INDEX mcp_tokens_family ON mcp_tokens USING btree (family);
CREATE INDEX mcp_tokens_revoked ON mcp_tokens USING btree (revoked_at);
CREATE UNIQUE INDEX notify_deliveries_dedupe ON notify_deliveries USING btree (dedupe_key);
CREATE INDEX notify_deliveries_due ON notify_deliveries USING btree (status, next_attempt_at);
CREATE INDEX notify_deliveries_retention ON notify_deliveries USING btree (status, created_at);
CREATE INDEX notify_deliveries_tenant ON notify_deliveries USING btree (tenant, created_at);
CREATE INDEX notify_subscriptions_due ON notify_subscriptions USING btree (status, last_evaluated_at);
CREATE INDEX notify_subscriptions_tenant ON notify_subscriptions USING btree (tenant, status);
CREATE INDEX posts_agent_time ON posts USING btree (agent_id, created_at DESC);
CREATE INDEX trades_agent_time ON trades USING btree (agent_id, created_at DESC);
CREATE INDEX trades_agent_userop ON trades USING btree (agent_id, user_op_hash);
CREATE INDEX trades_decision ON trades USING btree (decision_id);
CREATE INDEX trades_time ON trades USING btree (created_at DESC);
